/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.jdbc.sql;

import java.sql.SQLException;

import org.junit.jupiter.api.Test;

import com.sqlapp.AbstractDbTest;
import com.sqlapp.data.parameter.ParametersContext;

class JdbcBatchTableIterateHanderTest extends AbstractDbTest {

	private String CREATE_TABLE = """
			CREATE TABLE TAB
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  ,  TXT VARCHAR(256)
			)""";
	private String CREATE_TABLE_1 = """
			CREATE TABLE TAB_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_1_1 = """
			CREATE TABLE TAB_1_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB_1(ID)
			)""";
	private String CREATE_TABLE_2 = """
			CREATE TABLE TAB_2
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_2_1 = """
			CREATE TABLE TAB_2_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB_2(ID)
			)""";

	/**
	 * INSERTして自動生成されたキーを使って、そのままUPDATEを行う
	 * 
	 * @throws SQLException
	 */
	@Test
	void testInsertUpdateWithGeneratedKey() throws SQLException {
		final ParametersContext context = new ParametersContext();
		testDb(connection -> {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
			executeSql(connection, CREATE_TABLE);
			executeSql(connection, CREATE_TABLE_1);
			executeSql(connection, CREATE_TABLE_1_1);
			executeSql(connection, CREATE_TABLE_2);
			executeSql(connection, CREATE_TABLE_2_1);
//			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
//			assertTrue(schemaOption.isPresent());
//			Schema schema = schemaOption.get();
//			assertEquals(5, schema.getTables().size());
		}, (connection) -> {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
		});
	}

}
