/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.spanner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Duration;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.spanner.Spanner;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.ForeignKeyConstraint;
import com.sqlapp.data.schemas.UniqueConstraint;

/** Cloud Spanner emulator integration coverage for MetadataReader. */
class SpannerMetadataReaderTest {
	private static final GenericContainer<?> SPANNER = ReusableTestcontainers.configure(
			new GenericContainer<>(DockerImageName.parse(
					"gcr.io/cloud-spanner-emulator/emulator:latest"))
					.withExposedPorts(9010)
					.waitingFor(Wait.forListeningPort()
							.withStartupTimeout(Duration.ofMinutes(2))));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(SPANNER);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(SPANNER);
	}

	@Test
	void readsRepresentativeSchemaObjectsFromCurrentEmulator() throws Exception {
		try (Connection connection = createConnection();
				Statement statement = connection.createStatement()) {
			statement.execute("ALTER DATABASE `metadata-db` SET OPTIONS "
					+ "(default_sequence_kind='bit_reversed_positive')");
			statement.execute("""
					CREATE SEQUENCE metadata_sequence OPTIONS (
					 sequence_kind='bit_reversed_positive', start_with_counter=1000)
					""");
			statement.execute("""
					CREATE TABLE metadata_parent (
					 id INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
					 code STRING(30) NOT NULL,
					 amount NUMERIC
					) PRIMARY KEY (id)
					""");
			statement.execute("CREATE UNIQUE INDEX uq_metadata_parent_code "
					+ "ON metadata_parent(code)");
			statement.execute("""
					CREATE TABLE metadata_child (
					 id INT64 NOT NULL,
					 parent_id INT64 NOT NULL,
					 code STRING(30),
					 CONSTRAINT fk_metadata_child_parent FOREIGN KEY (parent_id)
					  REFERENCES metadata_parent (id)
					) PRIMARY KEY (id)
					""");
			statement.execute("CREATE INDEX idx_metadata_child_code "
					+ "ON metadata_child(code)");
			statement.execute("CREATE NULL_FILTERED INDEX idx_metadata_child_filtered "
					+ "ON metadata_child(code) STORING (parent_id)");
			statement.execute("""
					CREATE TABLE metadata_interleaved_child (
					 id INT64 NOT NULL,
					 child_id INT64 NOT NULL,
					 payload STRING(30)
					) PRIMARY KEY (id, child_id),
					INTERLEAVE IN PARENT metadata_parent ON DELETE CASCADE
					""");
			statement.execute("CREATE VIEW metadata_view SQL SECURITY INVOKER AS "
					+ "SELECT p.id, p.code FROM metadata_parent AS p");

			var dialect = DialectResolver.getInstance().getDialect(connection);
			assertInstanceOf(Spanner.class, dialect);
			var schemas = dialect.getCatalogReader().getSchemaReader()
					.getAllFull(connection);
			var schema = schemas.stream()
					.filter(s -> s.getTables().get("metadata_parent") != null)
					.findFirst().orElseThrow();
			var parent = schema.getTables().get("metadata_parent");
			assertTrue(parent.getColumns().get("id").isIdentity());
			var primaryKey = parent.getConstraints().stream()
					.filter(UniqueConstraint.class::isInstance)
					.map(UniqueConstraint.class::cast)
					.filter(UniqueConstraint::isPrimaryKey)
					.findFirst().orElseThrow();
			assertEquals("id", primaryKey.getColumns().get(0).getName());
			assertTrue(parent.getIndexes().get("uq_metadata_parent_code").isUnique());
			var child = schema.getTables().get("metadata_child");
			assertNotNull(child.getIndexes().get("idx_metadata_child_code"));
			var filteredIndex = child.getIndexes().get("idx_metadata_child_filtered");
			assertNotNull(filteredIndex);
			assertEquals(Boolean.TRUE,
					filteredIndex.getSpecifics().get("is_null_filtered", Boolean.class));
			assertEquals("parent_id", filteredIndex.getIncludes().get(0).getName());
			var foreignKey = child.getConstraints().stream()
					.filter(ForeignKeyConstraint.class::isInstance)
					.map(ForeignKeyConstraint.class::cast)
					.findFirst().orElseThrow();
			assertEquals("parent_id", foreignKey.getColumns().get(0).getName());
			assertEquals("id", foreignKey.getRelatedColumns().get(0).getName());
			var interleaved = schema.getTables().get("metadata_interleaved_child");
			assertNotNull(interleaved);
			assertEquals("metadata_parent", interleaved.getSpecifics().get("parent_table_name"));
			assertEquals("CASCADE", interleaved.getSpecifics().get("on_delete_action"));
			assertNotNull(schema.getSequences().get("metadata_sequence"));
			assertNotNull(schema.getViews().get("metadata_view"));
		}
	}

	private Connection createConnection() throws Exception {
		String url = "jdbc:cloudspanner://localhost:" + SPANNER.getMappedPort(9010)
				+ "/projects/test-project/instances/test-instance/databases/metadata-db"
				+ ";usePlainText=true;autoConfigEmulator=true";
		return DriverManager.getConnection(url);
	}
}
