/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.db2;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.Dialect;
import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.db2.Db2_1150;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.PartitioningType;
import com.sqlapp.data.schemas.Table;

/** Db2 11.5 compatibility coverage for the full metadata reader tree. */
class Db2_1150MetadataReaderTest {
	private static final SqlReadyDb2Container DB2 = new SqlReadyDb2Container(
			"icr.io/db2_community/db2:11.5.8.0");

	@BeforeAll
	static void startContainer() {
		DB2.start();
	}

	@AfterAll
	static void stopContainer() {
		if (!ReusableTestcontainers.isReuseEnabled()) {
			DB2.stop();
		}
	}

	@Test
	void testMetadataReaderOperatesOnDb2_11_5() throws SQLException {
		try (Connection connection = DB2.createConnection("");
				Statement statement = connection.createStatement()) {
				drop(statement, "DROP VIEW METADATA_COMPAT_VIEW");
			drop(statement, "DROP TRIGGER METADATA_COMPAT_TRIGGER");
			drop(statement, "DROP PROCEDURE METADATA_COMPAT_PROCEDURE");
			drop(statement, "DROP FUNCTION METADATA_COMPAT_FUNCTION");
			drop(statement, "DROP TABLE METADATA_COMPAT_CHILD");
			drop(statement, "DROP TABLE METADATA_COMPAT_PARENT");
			drop(statement, "DROP TABLE METADATA_COMPAT_AUDIT");
			drop(statement, "DROP TABLE METADATA_COMPAT_PARTITIONED");
			drop(statement, "DROP TABLE METADATA_COMPAT_MDC");
			drop(statement, "DROP TABLE METADATA_COMPAT_TYPED");
			drop(statement, "DROP TYPE METADATA_COMPAT_ADDRESS");
			drop(statement, "DROP TYPE METADATA_COMPAT_MONEY");
			drop(statement, "DROP SEQUENCE METADATA_COMPAT_SEQ");
			statement.execute("""
					CREATE DISTINCT TYPE METADATA_COMPAT_MONEY
					 AS DECIMAL(18, 2) WITH COMPARISONS
					""");
			statement.execute("""
					CREATE TYPE METADATA_COMPAT_ADDRESS AS (
					 STREET VARCHAR(100), POSTAL_CODE CHAR(5)) MODE DB2SQL
					""");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_PARENT (
					 ID BIGINT NOT NULL PRIMARY KEY, NAME VARCHAR(100))
					""");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_CHILD (
					 ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					 PARENT_ID BIGINT NOT NULL, AMOUNT DECIMAL(18,2),
					 CONSTRAINT CK_METADATA_COMPAT CHECK (AMOUNT >= 0),
					 CONSTRAINT FK_METADATA_COMPAT FOREIGN KEY (PARENT_ID)
					 REFERENCES METADATA_COMPAT_PARENT(ID))
					""");
			statement.execute("CREATE INDEX IDX_METADATA_COMPAT ON METADATA_COMPAT_CHILD(PARENT_ID)");
			statement.execute("CREATE SEQUENCE METADATA_COMPAT_SEQ START WITH 1");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_PARTITIONED (
					 ID BIGINT NOT NULL, BUCKET INTEGER NOT NULL)
					 PARTITION BY RANGE (BUCKET) (
					  PARTITION P_LOW STARTING FROM (MINVALUE) ENDING AT (99) INCLUSIVE,
					  PARTITION P_HIGH STARTING FROM (100) INCLUSIVE ENDING AT (MAXVALUE))
					""");
			statement.execute("CREATE VIEW METADATA_COMPAT_VIEW AS SELECT ID, PARENT_ID FROM METADATA_COMPAT_CHILD");
			statement.execute("CREATE TABLE METADATA_COMPAT_AUDIT (ID BIGINT)");
			statement.execute("""
					CREATE PROCEDURE METADATA_COMPAT_PROCEDURE(IN P_ID BIGINT)
					 LANGUAGE SQL BEGIN ATOMIC
					 INSERT INTO METADATA_COMPAT_AUDIT VALUES P_ID; END
					""");
			statement.execute("""
					CREATE FUNCTION METADATA_COMPAT_FUNCTION(P_AMOUNT DECIMAL(18,2))
					 RETURNS DECIMAL(18,2) LANGUAGE SQL DETERMINISTIC
					 BEGIN RETURN P_AMOUNT * 2; END
					""");
			statement.execute("""
					CREATE TRIGGER METADATA_COMPAT_TRIGGER AFTER INSERT
					 ON METADATA_COMPAT_CHILD REFERENCING NEW AS N FOR EACH ROW
					 INSERT INTO METADATA_COMPAT_AUDIT VALUES N.ID
					""");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_MDC (
					 REGION CHAR(2) NOT NULL, BUCKET INTEGER NOT NULL,
					 PAYLOAD VARCHAR(100))
					 ORGANIZE BY DIMENSIONS (REGION, BUCKET)
					""");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_TYPED (
					 ID BIGINT NOT NULL PRIMARY KEY,
					 AMOUNT METADATA_COMPAT_MONEY)
					""");

			Dialect dialect = DialectResolver.getInstance().getDialect(connection);
			assertInstanceOf(Db2_1150.class, dialect);
			String schemaName = DB2.getUsername().toUpperCase(Locale.ROOT);
			var schemaReader = dialect.getCatalogReader().getSchemaReader();
			schemaReader.setSchemaName(schemaName);
			Schema schema = schemaReader.getAllFull(connection).stream()
					.filter(current -> schemaName.equalsIgnoreCase(current.getName()))
					.findFirst().orElseThrow();
			Table child = schema.getTables().get("METADATA_COMPAT_CHILD");
			assertNotNull(child);
			assertNotNull(child.getConstraints().get("CK_METADATA_COMPAT"));
			assertNotNull(child.getConstraints().get("FK_METADATA_COMPAT"));
			assertNotNull(child.getIndexes().get("IDX_METADATA_COMPAT"));
			assertNotNull(schema.getSequences().get("METADATA_COMPAT_SEQ"));
			var view = schema.getViews().get("METADATA_COMPAT_VIEW");
			assertNotNull(view);
			assertTrue(String.join("\n", view.getDefinition())
					.toUpperCase(Locale.ROOT).contains("METADATA_COMPAT_CHILD"));
			var procedure = schema.getProcedures()
					.get("METADATA_COMPAT_PROCEDURE");
			assertNotNull(procedure);
			assertEquals(1, procedure.getArguments().size());
			assertTrue(String.join("\n", procedure.getStatement())
					.toUpperCase(Locale.ROOT).contains("METADATA_COMPAT_AUDIT"));
			var function = schema.getFunctions().get("METADATA_COMPAT_FUNCTION");
			assertNotNull(function);
			assertEquals(1, function.getArguments().size());
			assertTrue(String.join("\n", function.getStatement())
					.toUpperCase(Locale.ROOT).contains("P_AMOUNT"));
			var trigger = schema.getTriggers().get("METADATA_COMPAT_TRIGGER");
			assertNotNull(trigger);
			assertEquals("METADATA_COMPAT_CHILD", trigger.getTableName());
			assertTrue(String.join("\n", trigger.getDefinition())
					.toUpperCase(Locale.ROOT).contains("METADATA_COMPAT_AUDIT"));
			Table partitioned = schema.getTables()
					.get("METADATA_COMPAT_PARTITIONED");
			assertNotNull(partitioned);
			assertEquals(PartitioningType.Range,
					partitioned.getPartitioning().getPartitioningType());
			assertEquals(2, partitioned.getPartitioning().getPartitions().size());
			Table mdc = schema.getTables().get("METADATA_COMPAT_MDC");
			assertNotNull(mdc);
			assertEquals("C", mdc.getColumns().get("REGION")
					.getSpecifics().get("TYPE"));
			assertNotNull(mdc.getColumns().get("REGION")
					.getSpecifics().get("DIMENSION"));
			assertNotNull(mdc.getColumns().get("BUCKET")
					.getSpecifics().get("DIMENSION"));
			var money = schema.getDomains().get("METADATA_COMPAT_MONEY");
			assertNotNull(money);
			assertEquals(DataType.DECIMAL, money.getDataType());
			assertEquals("METADATA_COMPAT_MONEY", schema.getTables()
					.get("METADATA_COMPAT_TYPED").getColumns().get("AMOUNT")
					.getDataTypeName());
			var address = schema.getTypes().get("METADATA_COMPAT_ADDRESS");
			assertNotNull(address);
			assertEquals(2, address.getColumns().size());
			assertEquals(DataType.VARCHAR,
					address.getColumns().get("STREET").getDataType());
		}
	}

	private void drop(final Statement statement, final String sql)
			throws SQLException {
		try {
			statement.execute(sql);
		} catch (SQLException e) {
			if (!"42704".equals(e.getSQLState())) {
				throw e;
			}
		}
	}
}
