/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.db2;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.dialect.Dialect;
import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.db2.Db2_1150;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.PartitioningType;
import com.sqlapp.data.schemas.Table;

/** Db2 11.5 compatibility coverage for the full metadata reader tree. */
class Db2_1150MetadataReaderTest {
	private static final SqlReadyDb2Container DB2 = new SqlReadyDb2Container(
			"icr.io/db2_community/db2:11.5.8.0");

	@BeforeAll
	static void startContainer() {
		DB2.start();
	}

	@AfterAll
	static void stopContainer() {
		if (!ReusableTestcontainers.isReuseEnabled()) {
			DB2.stop();
		}
	}

	@Test
	void testMetadataReaderOperatesOnDb2_11_5() throws SQLException {
		try (Connection connection = DB2.createConnection("");
				Statement statement = connection.createStatement()) {
			drop(statement, "DROP VIEW METADATA_COMPAT_VIEW");
			drop(statement, "DROP TABLE METADATA_COMPAT_CHILD");
			drop(statement, "DROP TABLE METADATA_COMPAT_PARENT");
			drop(statement, "DROP TABLE METADATA_COMPAT_PARTITIONED");
			drop(statement, "DROP SEQUENCE METADATA_COMPAT_SEQ");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_PARENT (
					 ID BIGINT NOT NULL PRIMARY KEY, NAME VARCHAR(100))
					""");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_CHILD (
					 ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					 PARENT_ID BIGINT NOT NULL, AMOUNT DECIMAL(18,2),
					 CONSTRAINT CK_METADATA_COMPAT CHECK (AMOUNT >= 0),
					 CONSTRAINT FK_METADATA_COMPAT FOREIGN KEY (PARENT_ID)
					 REFERENCES METADATA_COMPAT_PARENT(ID))
					""");
			statement.execute("CREATE INDEX IDX_METADATA_COMPAT ON METADATA_COMPAT_CHILD(PARENT_ID)");
			statement.execute("CREATE SEQUENCE METADATA_COMPAT_SEQ START WITH 1");
			statement.execute("""
					CREATE TABLE METADATA_COMPAT_PARTITIONED (
					 ID BIGINT NOT NULL, BUCKET INTEGER NOT NULL)
					 PARTITION BY RANGE (BUCKET) (
					  PARTITION P_LOW STARTING FROM (MINVALUE) ENDING AT (99) INCLUSIVE,
					  PARTITION P_HIGH STARTING FROM (100) INCLUSIVE ENDING AT (MAXVALUE))
					""");
			statement.execute("CREATE VIEW METADATA_COMPAT_VIEW AS SELECT ID, PARENT_ID FROM METADATA_COMPAT_CHILD");

			Dialect dialect = DialectResolver.getInstance().getDialect(connection);
			assertInstanceOf(Db2_1150.class, dialect);
			String schemaName = DB2.getUsername().toUpperCase(Locale.ROOT);
			var schemaReader = dialect.getCatalogReader().getSchemaReader();
			schemaReader.setSchemaName(schemaName);
			Schema schema = schemaReader.getAllFull(connection).stream()
					.filter(current -> schemaName.equalsIgnoreCase(current.getName()))
					.findFirst().orElseThrow();
			Table child = schema.getTables().get("METADATA_COMPAT_CHILD");
			assertNotNull(child);
			assertNotNull(child.getConstraints().get("CK_METADATA_COMPAT"));
			assertNotNull(child.getConstraints().get("FK_METADATA_COMPAT"));
			assertNotNull(child.getIndexes().get("IDX_METADATA_COMPAT"));
			assertNotNull(schema.getSequences().get("METADATA_COMPAT_SEQ"));
			assertNotNull(schema.getViews().get("METADATA_COMPAT_VIEW"));
			Table partitioned = schema.getTables()
					.get("METADATA_COMPAT_PARTITIONED");
			assertNotNull(partitioned);
			assertEquals(PartitioningType.Range,
					partitioned.getPartitioning().getPartitioningType());
			assertEquals(2, partitioned.getPartitioning().getPartitions().size());
		}
	}

	private void drop(final Statement statement, final String sql)
			throws SQLException {
		try {
			statement.execute(sql);
		} catch (SQLException e) {
			if (!"42704".equals(e.getSQLState())) {
				throw e;
			}
		}
	}
}
