/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.db2;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.sql.Connection;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkInsertResolver;
import com.sqlapp.jdbc.bulk.BulkOption;

/** Exercises JCC JDBC batching against DB2 Community 12.1.5. */
class Db2BulkInsertTest {
	private static final SqlReadyDb2Container DB2 = new SqlReadyDb2Container(
			"icr.io/db2_community/db2:12.1.5.0");

	@BeforeAll
	static void startContainer() {
		DB2.start();
	}

	@AfterAll
	static void stopContainer() {
		if (!ReusableTestcontainers.isReuseEnabled()) {
			DB2.stop();
		}
	}

	@Test
	void insertsBatchesAndGeneratedByDefaultIdentity() throws Exception {
		try (Connection connection = DB2.createConnection("");
				var statement = connection.createStatement()) {
			try {
				statement.execute("DROP TABLE SQLAPP_BULK_DB2");
			} catch (java.sql.SQLException ignored) {
				// The isolated test database can start without the table.
			}
			statement.execute("CREATE TABLE SQLAPP_BULK_DB2 ("
					+ "ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
					+ "TXT VARCHAR(200), NULLABLE_VALUE VARCHAR(20), "
					+ "EMPTY_VALUE VARCHAR(20), PAYLOAD VARCHAR(20) FOR BIT DATA)");
			final Table generated = createTable();
			generated.getRows().add(row -> {
				row.put("TXT", "日本語\nline");
				row.put("NULLABLE_VALUE", null);
				row.put("EMPTY_VALUE", "");
				row.put("PAYLOAD", new byte[] { 0, (byte) 0xff });
			});
			assertEquals(1, BulkInsertResolver.execute(connection, generated,
					BulkOption.builder().batchSize(2).build()));

			final Table explicit = createTable();
			explicit.getRows().add(row -> {
				row.put("ID", 42);
				row.put("TXT", "explicit");
				row.put("EMPTY_VALUE", "");
				row.put("PAYLOAD", new byte[] { 1 });
			});
			assertEquals(1, BulkInsertResolver.execute(connection, explicit,
					BulkOption.builder().keepIdentity(true).build()));

			try (var resultSet = statement.executeQuery("SELECT ID, TXT, NULLABLE_VALUE, "
					+ "EMPTY_VALUE, PAYLOAD FROM SQLAPP_BULK_DB2 ORDER BY ID")) {
				resultSet.next();
				assertEquals(1, resultSet.getInt("ID"));
				assertEquals("日本語\nline", resultSet.getString("TXT"));
				assertNull(resultSet.getString("NULLABLE_VALUE"));
				assertEquals("", resultSet.getString("EMPTY_VALUE"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff }, resultSet.getBytes("PAYLOAD"));
				resultSet.next();
				assertEquals(42, resultSet.getInt("ID"));
			}
		}
	}

	private static Table createTable() {
		final Table table = new Table("SQLAPP_BULK_DB2");
		table.getColumns().add(new Column("ID").setDataType(DataType.INT).setIdentity(true));
		table.getColumns().add(new Column("TXT").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("NULLABLE_VALUE").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("EMPTY_VALUE").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("PAYLOAD").setDataType(DataType.VARBINARY));
		return table;
	}
}
