/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.db2;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.dialect.Dialect;
import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.db2.Db2_1215;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.ForeignKeyConstraint;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.data.schemas.UniqueConstraint;

/** Db2 12.1.5 integration coverage for the metadata reader tree. */
class Db2MetadataReaderTest {
	private static final String IMAGE =
			"icr.io/db2_community/db2:12.1.5.0";
	private static final SqlReadyDb2Container DB2 =
			new SqlReadyDb2Container(IMAGE);

	@BeforeAll
	static void startContainer() {
		DB2.start();
	}

	@AfterAll
	static void stopContainer() {
		if (!ReusableTestcontainers.isReuseEnabled()) {
			DB2.stop();
		}
	}

	@Test
	void testReadsRepresentativeSchemaObjectsFromLatestDb2()
			throws SQLException {
		try (Connection connection = DB2.createConnection("")) {
			createSchemaObjects(connection);
			Dialect dialect = DialectResolver.getInstance().getDialect(connection);
			assertInstanceOf(Db2_1215.class, dialect);

			String schemaName = DB2.getUsername().toUpperCase(Locale.ROOT);
			var schemaReader = dialect.getCatalogReader().getSchemaReader();
			schemaReader.setSchemaName(schemaName);
			Schema schema = schemaReader.getAllFull(connection).stream()
					.filter(current -> schemaName.equalsIgnoreCase(current.getName()))
					.findFirst().orElseThrow(() -> new AssertionError(
							"Db2 test schema was not loaded."));

			Table parent = schema.getTables().get("METADATA_PARENT");
			assertNotNull(parent);
			assertEquals("Metadata parent table", parent.getRemarks());
			UniqueConstraint primaryKey = assertInstanceOf(
					UniqueConstraint.class,
					parent.getConstraints().get("PK_METADATA_PARENT"));
			assertEquals(2, primaryKey.getColumns().size());
			assertEquals("Display name",
					parent.getColumns().get("NAME").getRemarks());

			Table child = schema.getTables().get("METADATA_CHILD");
			assertNotNull(child);
			assertTrue(child.getColumns().get("ID").isIdentity());
			assertTrue(child.getColumns().get("CODE").isNotNull());
			assertNotNull(child.getConstraints().get("UK_METADATA_CHILD_CODE"));
			assertNotNull(child.getConstraints().get("CK_METADATA_CHILD_AMOUNT"));
			ForeignKeyConstraint foreignKey = assertInstanceOf(
					ForeignKeyConstraint.class,
					child.getConstraints().get("FK_METADATA_CHILD_PARENT"));
			assertEquals(2, foreignKey.getColumns().size());
			assertEquals(2, foreignKey.getRelatedColumns().size());
			assertNotNull(child.getIndexes().get("IDX_METADATA_CHILD_PARENT"));
			assertNotNull(schema.getSequences().get("METADATA_SEQ"));
			assertNotNull(schema.getViews().get("METADATA_VIEW"));
			assertNotNull(schema.getProcedures().get("METADATA_PROCEDURE"));
			assertNotNull(schema.getFunctions().get("METADATA_FUNCTION"));
			assertNotNull(schema.getTriggers().get("METADATA_TRIGGER"));
			assertNotNull(schema.getSynonyms().get("METADATA_PARENT_ALIAS"));
		}
	}

	private void createSchemaObjects(final Connection connection)
			throws SQLException {
		try (Statement statement = connection.createStatement()) {
			drop(statement, "DROP TRIGGER METADATA_TRIGGER");
			drop(statement, "DROP PROCEDURE METADATA_PROCEDURE");
			drop(statement, "DROP FUNCTION METADATA_FUNCTION");
			drop(statement, "DROP VIEW METADATA_VIEW");
			drop(statement, "DROP ALIAS METADATA_PARENT_ALIAS");
			drop(statement, "DROP TABLE METADATA_CHILD");
			drop(statement, "DROP TABLE METADATA_PARENT");
			drop(statement, "DROP TABLE METADATA_AUDIT");
			drop(statement, "DROP SEQUENCE METADATA_SEQ");
			statement.execute("CREATE SEQUENCE METADATA_SEQ START WITH 50 INCREMENT BY 10");
			statement.execute("""
					CREATE TABLE METADATA_PARENT (
					 ID BIGINT NOT NULL, REGION CHAR(2) NOT NULL,
					 NAME VARCHAR(100) NOT NULL,
					 CONSTRAINT PK_METADATA_PARENT PRIMARY KEY (ID, REGION))
					""");
			statement.execute("""
					CREATE TABLE METADATA_CHILD (
					 ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
					 PARENT_ID BIGINT NOT NULL, PARENT_REGION CHAR(2) NOT NULL,
					 CODE VARCHAR(40) DEFAULT 'unknown' NOT NULL,
					 AMOUNT DECIMAL(18, 2) NOT NULL,
					 CONSTRAINT PK_METADATA_CHILD PRIMARY KEY (ID),
					 CONSTRAINT UK_METADATA_CHILD_CODE UNIQUE (CODE),
					 CONSTRAINT CK_METADATA_CHILD_AMOUNT CHECK (AMOUNT >= 0),
					 CONSTRAINT FK_METADATA_CHILD_PARENT FOREIGN KEY
					 (PARENT_ID, PARENT_REGION) REFERENCES METADATA_PARENT(ID, REGION))
					""");
			statement.execute("CREATE INDEX IDX_METADATA_CHILD_PARENT ON METADATA_CHILD(PARENT_ID DESC, CODE)");
			statement.execute("COMMENT ON TABLE METADATA_PARENT IS 'Metadata parent table'");
			statement.execute("COMMENT ON COLUMN METADATA_PARENT.NAME IS 'Display name'");
			statement.execute("CREATE VIEW METADATA_VIEW AS SELECT ID, CODE FROM METADATA_CHILD");
			statement.execute("CREATE ALIAS METADATA_PARENT_ALIAS FOR METADATA_PARENT");
			statement.execute("CREATE TABLE METADATA_AUDIT (ID BIGINT)");
			statement.execute("""
					CREATE PROCEDURE METADATA_PROCEDURE(IN P_PARENT_ID BIGINT)
					 LANGUAGE SQL BEGIN ATOMIC INSERT INTO METADATA_AUDIT VALUES P_PARENT_ID; END
					""");
			statement.execute("""
					CREATE FUNCTION METADATA_FUNCTION(P_AMOUNT DECIMAL(18,2))
					 RETURNS DECIMAL(18,2) LANGUAGE SQL DETERMINISTIC RETURN P_AMOUNT * 2
					""");
			statement.execute("""
					CREATE TRIGGER METADATA_TRIGGER AFTER INSERT ON METADATA_CHILD
					 REFERENCING NEW AS N FOR EACH ROW
					 INSERT INTO METADATA_AUDIT VALUES N.ID
					""");
		}
	}

	private void drop(final Statement statement, final String sql)
			throws SQLException {
		try {
			statement.execute(sql);
		} catch (SQLException e) {
			if (!"42704".equals(e.getSQLState())) {
				throw e;
			}
		}
	}
}
