/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.command.jdbc.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Optional;
import java.util.function.BiConsumer;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.test.AbstractDbCommandTest;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.function.SQLConsumer;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession.TableOperationMode;
import com.zaxxer.hikari.HikariDataSource;

class JdbcTreeDataSessionNormalizationTest extends AbstractDbCommandTest {

	private String CREATE_CUSTOMERS = """
			CREATE TABLE CUSTOMERS
			(
				  ID VARCHAR(256) PRIMARY KEY
				, CUSTOMER_NAME VARCHAR(256) NOT NULL
				, CREATED_AT DATETIME NOT NULL
				, CONSTRAINT UK_CUSTOMERS UNIQUE (CUSTOMER_NAME)
			)""";
	private String CREATE_PRODUCTS = """
			CREATE TABLE PRODUCTS
			(
				  ID VARCHAR(256) PRIMARY KEY
				, PRODUCT_NAME VARCHAR(256) NOT NULL
				, CREATED_AT DATETIME NOT NULL
				, CONSTRAINT UK_PRODUCTS UNIQUE (PRODUCT_NAME)
			)""";
	private String CREATE_ORDERS = """
			CREATE TABLE ORDERS
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , CUSTOMER_ID VARCHAR(256) NOT NULL
				  , CREATED_AT DATETIME NOT NULL
				  , CONSTRAINT FK_ORDER_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
			)""";
	private String CREATE_ORDER_DETAILS = """
			CREATE TABLE ORDER_DETAILS
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  , PRODUCT_ID VARCHAR(256) NOT NULL
				  , CREATED_AT DATETIME NOT NULL
				  , CONSTRAINT FK_ORDER_DETAILS_1 FOREIGN KEY (PARENT_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE
			)""";
	private String CREATE_FLAT_ORDERS = """
			CREATE TABLE FLAT_ORDERS
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , CUSTOMER_NAME VARCHAR(256) NOT NULL
				  , PRODUCT_NAME VARCHAR(256) NOT NULL
				  , CREATED_AT DATETIME NOT NULL
			)""";

	@Test
	void testInsertUpdateWithCombinedPK() throws SQLException {
		try (HikariDataSource ds = newInternalDataSource(); Connection connection = ds.getConnection();) {
			System.out.println("---------------------------INSERT------------------------------------");
			this.dropTables(connection, "ORDER_DETAILS");
			this.dropTables(connection, "ORDERS");
			this.dropTables(connection, "PRODUCTS");
			this.dropTables(connection, "CUSTOMERS");
			this.dropTables(connection, "FLAT_ORDERS");
			executeSql(connection, CREATE_CUSTOMERS);
			executeSql(connection, CREATE_PRODUCTS);
			executeSql(connection, CREATE_ORDERS);
			executeSql(connection, CREATE_ORDER_DETAILS);
			executeSql(connection, CREATE_FLAT_ORDERS);
			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
			assertTrue(schemaOption.isPresent());
			Schema schema = schemaOption.get();
			final Table customers = schema.getTables().get("CUSTOMERS");
			final Table products = schema.getTables().get("PRODUCTS");
			final Table orders = schema.getTables().get("ORDERS");
			final Table orderDetails = schema.getTables().get("ORDER_DETAILS");
			final Table flatOrders = schema.getTables().get("FLAT_ORDERS");
			// TEST DATA(CUSTOMERS)
			insert(connection, customers, session -> {
				session.setTableOperationMode(TableOperationMode.INSERT);
			}, (i, row) -> {
				row.put("ID", "" + i);
				row.put("CUSTOMER_NAME", "CUSTOMER_NAME_" + i);
			});
			customers.read(connection);
			assertTrue(customers.getRows().size() > 0);
			// TEST DATA(PRODUCTS)
			insert(connection, products, session -> {
				session.setTableOperationMode(TableOperationMode.INSERT);
			}, (i, row) -> {
				row.put("ID", "" + i);
				row.put("PRODUCT_NAME", "PRODUCT_NAME" + i);
			});
			products.read(connection);
			assertTrue(products.getRows().size() > 0);
			String selectForFlatOrders = """
					SELECT
					  CUSTOMER_NAME
					,  PRODUCT_NAME
					FROM CUSTOMERS,PRODUCTS
					ORDER BY CUSTOMER_NAME, PRODUCT_NAME
					""";
			// TEST DATA(FLAT_ORDERS)
			JdbcTreeDataSession flatOrdeSession = new JdbcTreeDataSession(connection, flatOrders);
			flatOrdeSession.setTableOperationMode(TableOperationMode.INSERT);
			flatOrdeSession.select(flatOrders, selectForFlatOrders);
			try (flatOrdeSession) {
				flatOrdeSession.readAll((tbl, rowNo, row) -> {

				});
			}
			flatOrders.read(connection);
			assertTrue(flatOrders.getRows().size() > 0);
			// Normalization
			JdbcTreeDataSession session = new JdbcTreeDataSession(connection, orders, orderDetails);
			initializeSession(session);
			String selectForOrders = """
					SELECT
					  c.ID AS CUSTOMER_ID
					FROM FLAT_ORDERS fo
					INNER JOIN CUSTOMERS c
					  ON (fo.CUSTOMER_NAME=c.CUSTOMER_NAME)
					GROUP BY c.ID
					ORDER BY c.ID
					""";
			session.select(orders, selectForOrders);
			String selectForOrderDetails = """
					SELECT
					  p.ID AS PRODUCT_ID
					FROM FLAT_ORDERS fo
					INNER JOIN CUSTOMERS c
					  ON (fo.CUSTOMER_NAME=c.CUSTOMER_NAME)
					INNER JOIN PRODUCTS p
					  ON (fo.PRODUCT_NAME=p.PRODUCT_NAME)
					WHERE 1=1
					  /*ROWS=(target=ROOT;columns=(CUSTOMER_ID);mapping=(CUSTOMER_ID->ID);prefix=c.)*/
					ORDER BY c.ID, p.ID
					""";
			session.select(orderDetails, selectForOrderDetails);
			session.setTableOperationMode(TableOperationMode.INSERT);
			try (session) {
				session.readAll();
			}
			orders.read(connection);
			orderDetails.read(connection);
			assertEquals(3, orders.getRows().size());
			assertEquals(9, orderDetails.getRows().size());
		}
	}

	private void insert(Connection connection, Table table, SQLConsumer<JdbcTreeDataSession> sessionHandler,
			BiConsumer<Integer, Row> rowHandler) throws SQLException {
		JdbcTreeDataSession session = new JdbcTreeDataSession(connection, table);
		initializeSession(session);
		sessionHandler.accept(session);
		try (session) {
			for (int i = 0; i < 3; i++) {
				Row row = session.newRow(table);
				rowHandler.accept(i, row);
			}
		}
	}

	private void initializeSession(JdbcTreeDataSession session) {
		session.setNewRowInitializer(row -> {
			row.put("CREATED_AT", LocalDateTime.now());
		});
		session.setSqlHandler((t, sqlType, sql) -> {
			System.out.println("table=" + t.getName() + ", sqlType=" + sqlType);
			System.out.println(sql);
			return sql;
		});
		session.setRootBatchSize(10);
		session.setCommitEveryRootBatches(5);
		session.setBeforeRootBatchHandler((batchCounter, tbl, rows) -> {
			System.out.println("BeforeRootBatch batchCount=" + batchCounter);
			rows.forEach(row -> System.out.println(row));
			assertTrue(session.getRootBatchSize() >= tbl.getRows().size());
		});
		session.setAfterRootBatchHandler((batchCounter, tbl, rows) -> {
			System.out.println("AfterRootBatch batchCount=" + batchCounter);
			rows.forEach(row -> System.out.println(row));
			assertTrue(session.getRootBatchSize() >= rows.size());
		});
		session.setBeforeCommitEveryRootBatchesHandler((commitCounter, row) -> {
			System.out.println("BeforeCommitEveryRootBatches commitCount=" + commitCounter);
		});
		session.setAfterCommitEveryRootBatchesHandler((commitCounter, row) -> {
			System.out.println("AfterCommitEveryRootBatches commitCount=" + commitCounter + ", lastRow=" + row);
		});
		session.setPreparedStatementBeforeExecuteHandler(statement -> {
			System.out.println(statement);
		});
	}
}