/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.command.jdbc.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Optional;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.test.AbstractDbCommandTest;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.data.schemas.TableRelationTreeHolder;
import com.sqlapp.data.schemas.function.SQLExceptionConsumer;
import com.sqlapp.jdbc.sql.JdbcBatchTreeUpdateHandler;
import com.sqlapp.jdbc.sql.JdbcBatchTreeUpdateHandler.TableUpdateMode;
import com.zaxxer.hikari.HikariDataSource;

class JdbcBatchTreeUpdateHandlerIdentityUKTest extends AbstractDbCommandTest {

	private String CREATE_TABLE = """
			CREATE TABLE TAB
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				, UK VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, CONSTRAINT TAB_UK UNIQUE (UK)
			)""";
	private String CREATE_TABLE_1 = """
			CREATE TABLE TAB_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 4 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, UK VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB(ID)
				, CONSTRAINT TAB_1_UK UNIQUE (PARENT_ID, UK)
			)""";
	private String CREATE_TABLE_1_1 = """
			CREATE TABLE TAB_1_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 5 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, UK VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_1(ID)
				, CONSTRAINT TAB_1_1_UK UNIQUE (PARENT_ID, UK)
			)""";
	private String CREATE_TABLE_2 = """
			CREATE TABLE TAB_2
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 7 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, UK VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB(ID)
				, CONSTRAINT TAB_2_UK UNIQUE (PARENT_ID, UK)
			)""";
	private String CREATE_TABLE_2_1 = """
			CREATE TABLE TAB_2_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 7 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, UK VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_2(ID)
				, CONSTRAINT TAB_2_1_UK UNIQUE (PARENT_ID, UK)
			)""";

	/**
	 * Register data from multiple tables in a hierarchical structure using JDBC
	 * batch inserts, while automatically managing the hierarchy and setting foreign
	 * keys.
	 * 
	 * @throws SQLException
	 */
	@Test
	void testInsertUpdateWithGeneratedKey() throws SQLException {
		try (HikariDataSource ds = newInternalDataSource(); Connection connection = ds.getConnection();) {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
			executeSql(connection, CREATE_TABLE);
			executeSql(connection, CREATE_TABLE_1);
			executeSql(connection, CREATE_TABLE_1_1);
			executeSql(connection, CREATE_TABLE_2);
			executeSql(connection, CREATE_TABLE_2_1);
			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
			assertTrue(schemaOption.isPresent());
			Schema schema = schemaOption.get();
			TableRelationTreeHolder tableRelationTreeHolder = new TableRelationTreeHolder(schema.getTables());
			JdbcBatchTreeUpdateHandler handler = new JdbcBatchTreeUpdateHandler(connection, tableRelationTreeHolder);
			handler.setTableUpdateMode(TableUpdateMode.INSERT);
			handler.setNewRowInitializer(row -> {
				row.put("CREATED_AT", LocalDateTime.now());
			});
			handler.setSqlHandler((t, sqlType, sql) -> {
				System.out.println("table=" + t.getName() + ", sqlType=" + sqlType);
				System.out.println(sql);
				return sql;
			});
			handler.setRootBatchSize(3);
			handler.setCommitEveryRoots(2);
			boolean[] hasRootBatchSizeRows = new boolean[1];
			hasRootBatchSizeRows[0] = false;
			long[] batchCounterHolder = new long[1];
			long[] commitCounterHolder = new long[1];
			handler.setBeforeRootBatchHandler((batchCounter, table, rows) -> {
				System.out.println("BeforeRootBatch batchCount=" + batchCounter);
				rows.forEach(row -> System.out.println(row));
				assertTrue(handler.getRootBatchSize() >= table.getRows().size());
			});
			handler.setAfterRootBatchHandler((batchCounter, table, rows) -> {
				System.out.println("AfterRootBatch batchCount=" + batchCounter);
				rows.forEach(row -> System.out.println(row));
				assertTrue(handler.getRootBatchSize() >= rows.size());
				if (handler.getRootBatchSize() == rows.size()) {
					hasRootBatchSizeRows[0] = true;
				}
				batchCounterHolder[0] = batchCounter;
			});
			handler.setBeforeCommitEveryRootsHandler((commitCounter, row) -> {
				System.out.println("BeforeCommitEveryRoots commitCount=" + commitCounter);
				commitCounterHolder[0] = commitCounter;
			});
			handler.setAfterCommitEveryRootsHandler((commitCounter, row) -> {
				System.out.println("AfterCommitEveryRoots commitCount=" + commitCounter + ", lastRow=" + row);
				commitCounterHolder[0] = commitCounter;
			});
			final Table tab = schema.getTables().get("TAB");
			final Table tab1 = schema.getTables().get("TAB_1");
			final Table tab1_1 = schema.getTables().get("TAB_1_1");
			final Table tab2 = schema.getTables().get("TAB_2");
			final Table tab2_1 = schema.getTables().get("TAB_2_1");
			System.out.println("---------------------------INSERT------------------------------------");
			int loop = 3;
			try (handler) {
				for (int i = 0; i < loop; i++) {
					Table current = tab;
					Row row = handler.newRow(current);
					row.put("TXT", current.getName() + "_TXT_" + i);// If the number of calls to this method in the root
																	// hierarchy exceeds the rootBatchSize, automatic
																	// JDBC
																	// batch processing will occur.
					row.put("UK", "UK" + i);
					for (int j = 0; j < 2; j++) {
						current = tab1;
						row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j);
						row.put("UK", "UK" + j);
						for (int k = 0; k < 3; k++) {
							current = tab1_1;
							row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("UK", "UK" + k);
							row.put("TXT", current.getName() + "_TXT_" + k);
						}
					}
					for (int j = 0; j < 4; j++) {
						current = tab2;
						row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j);
						row.put("UK", "UK" + j);
						for (int k = 0; k < 2; k++) {
							current = tab2_1;
							row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("UK", "UK" + k);
							row.put("TXT", current.getName() + "_TXT_" + k);
						}
					}
				}
			}
			assertEquals(0, tab.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(0, tab2.getRows().size());
			assertEquals(0, tab2_1.getRows().size());
			assertEquals(1, batchCounterHolder[0]);
			assertEquals(1, commitCounterHolder[0]);
			assertTrue(hasRootBatchSizeRows[0]);
			Table table = tab;
			table.read(connection);
			int i = 0;
			assertEquals(loop, table.getRows().size());
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + i, row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				i++;
			}
			table = tab1;
			table.read(connection);
			assertEquals(6, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab1_1;
			table.read(connection);
			assertEquals(18, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 3), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab1.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2;
			table.read(connection);
			assertEquals(12, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 4), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2_1;
			table.read(connection);
			assertEquals(24, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab2.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			System.out.println("---------------------------UPDATE------------------------------------");
			tab.getRows().clear();
			tab1.getRows().clear();
			tab1_1.getRows().clear();
			tab2.getRows().clear();
			tab2_1.getRows().clear();
			batchCounterHolder[0] = 0;
			commitCounterHolder[0] = 0;
			handler.setTableUpdateMode(TableUpdateMode.UPDATE);
			// handler.getTableOptions().setUpdateKeyColumnsMatchingStrategy((t) ->
			// ColumnSelectionStrategy.UNIQUE_KEY);
			try (handler) {
				for (i = 0; i < (loop + 1); i++) {
					Table current = tab;
					Row row = handler.newRow(current);
					row.put("TXT", current.getName() + "_TXT_" + i + "_UPDATED");// If the number of calls to this
																					// method in the root
					// hierarchy exceeds the rootBatchSize, automatic
					// JDBC
					// batch processing will occur.
					row.put("UK", "UK" + i);
					for (int j = 0; j < 3; j++) {
						current = tab1;
						row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j + "_UPDATED");
						row.put("UK", "UK" + j);
						for (int k = 0; k < 3; k++) {
							current = tab1_1;
							row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("TXT", current.getName() + "_TXT_" + k + "_UPDATED");
							row.put("UK", "UK" + k);
						}
					}
					for (int j = 0; j < 5; j++) {
						current = tab2;
						row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j + "_UPDATED");
						row.put("UK", "UK" + j);
						for (int k = 0; k < 2; k++) {
							current = tab2_1;
							row = handler.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("TXT", current.getName() + "_TXT_" + k + "_UPDATED");
							row.put("UK", "UK" + k);
						}
					}
				}
			}
			assertEquals(0, tab.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(0, tab2.getRows().size());
			assertEquals(0, tab2_1.getRows().size());
			assertEquals(2, batchCounterHolder[0]);
			assertEquals(2, commitCounterHolder[0]);
			assertTrue(hasRootBatchSizeRows[0]);
			table = tab;
			table.read(connection);
			i = 0;
			assertEquals(loop, table.getRows().size());
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + i + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				i++;
			}
			table = tab1;
			table.read(connection);
			assertEquals(6, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2) + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab1_1;
			table.read(connection);
			assertEquals(18, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 3) + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab1.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2;
			table.read(connection);
			assertEquals(12, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 4) + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2_1;
			table.read(connection);
			assertEquals(24, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2) + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab2.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}

		}
	}

	private void test(SQLExceptionConsumer<Connection> cons, SQLExceptionConsumer<Connection> finCons)
			throws SQLException {
		try (HikariDataSource ds = newInternalDataSource(); Connection conn = ds.getConnection();) {
			cons.accept(conn);
			finCons.accept(conn);
		}
	}

}
