/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.command.jdbc.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.test.AbstractDbCommandTest;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.data.schemas.function.SQLExceptionConsumer;
import com.sqlapp.jdbc.sql.JdbcTreeDataCopySession;
import com.sqlapp.jdbc.sql.JdbcTreeDataCopySession.HoldCursorStrategy;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession.TableOperationMode;
import com.sqlapp.util.CommonUtils;
import com.zaxxer.hikari.HikariDataSource;

class JdbcTreeDataCopySessionTest extends AbstractDbCommandTest {

	private String CREATE_TABLE = """
			CREATE TABLE TAB
			(
				    PK_COL1 VARCHAR(256)
				  , PK_COL2 VARCHAR(256)
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				  , PRIMARY KEY (PK_COL1, PK_COL2)
			)""";
	private String CREATE_TABLE_1 = """
			CREATE TABLE TAB_1
			(
				    PK_COL1 VARCHAR(256)
				  , PK_COL2 VARCHAR(256)
				  , PK_COL3 VARCHAR(256)
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				  , PRIMARY KEY (PK_COL1, PK_COL2, PK_COL3)
				  , FOREIGN KEY(PK_COL1, PK_COL2) REFERENCES TAB (PK_COL1, PK_COL2) ON DELETE CASCADE
			)""";
	private String CREATE_TABLE_1_1 = """
			CREATE TABLE TAB_1_1
			(
				    PK_COL1A VARCHAR(256)
				  , PK_COL2A VARCHAR(256)
				  , PK_COL3A VARCHAR(256)
				  , PK_COL4A VARCHAR(256)
				  , TXT1 VARCHAR(256)
				  , TXT2 VARCHAR(256)
				  , TXT3 VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				  , PRIMARY KEY (PK_COL1A, PK_COL2A, PK_COL3A, PK_COL4A)
				  , FOREIGN KEY (PK_COL1A, PK_COL2A, PK_COL3A) REFERENCES TAB_1 (PK_COL1, PK_COL2, PK_COL3) ON DELETE CASCADE
			)""";

	private String CREATE_TABLE_TO = """
			CREATE TABLE TAB_TO
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				, PK_COL1 VARCHAR(256)
				, PK_COL2 VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, CONSTRAINT TAB_TO_UK UNIQUE (PK_COL1, PK_COL2)
			)""";
	private String CREATE_TABLE_1_TO = """
			CREATE TABLE TAB_1_TO
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 4 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, PK_COL3 VARCHAR(256)
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_TO(ID)
				, CONSTRAINT TAB_1_TO_UK UNIQUE (PARENT_ID, PK_COL3)
			)""";
	private String CREATE_TABLE_1_1_TO = """
			CREATE TABLE TAB_1_1_TO
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 5 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, PK_COL4A VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_1_TO(ID)
				, CONSTRAINT TAB_1_1_TO_UK UNIQUE (PARENT_ID, PK_COL4A)
			)""";
	private String CREATE_TABLE_1_1_1_TO = """
			CREATE TABLE TAB_1_1_1_TO
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 5 ) PRIMARY KEY
				, PARENT_ID INT NOT NULL
				, ROW_NO INT NOT NULL
				, TXT VARCHAR(256)
				, CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_1_1_TO(ID)
			)""";

	void testCopyAndNormalizeHierarchicalData(int rowSize1, int rowSize2, int rowSize3,
			Consumer<JdbcTreeDataCopySession> initializer) throws SQLException {
		test(connection -> {
			executeSql(connection, CREATE_TABLE);
			executeSql(connection, CREATE_TABLE_1);
			executeSql(connection, CREATE_TABLE_1_1);
			executeSql(connection, CREATE_TABLE_TO);
			executeSql(connection, CREATE_TABLE_1_TO);
			executeSql(connection, CREATE_TABLE_1_1_TO);
			executeSql(connection, CREATE_TABLE_1_1_1_TO);
			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
			assertTrue(schemaOption.isPresent());
			Schema schema = schemaOption.get();
			List<Table> tables = CommonUtils.list();
			final Table tab = schema.getTables().get("TAB");
			final Table tab1 = schema.getTables().get("TAB_1");
			final Table tab1_1 = schema.getTables().get("TAB_1_1");
			tables.add(tab);
			tables.add(tab1);
			tables.add(tab1_1);
			JdbcTreeDataSession source = createDate(connection, tables, rowSize1, rowSize2, rowSize3);
			tables.clear();
			final Table tabTo = schema.getTables().get("TAB_TO");
			final Table tab1To = schema.getTables().get("TAB_1_TO");
			final Table tab1_1To = schema.getTables().get("TAB_1_1_TO");
			final Table tab1_1_1To = schema.getTables().get("TAB_1_1_1_TO");
			tables.add(tabTo);
			tables.add(tab1To);
			tables.add(tab1_1To);
			tables.add(tab1_1_1To);
			JdbcTreeDataSession session = new JdbcTreeDataSession(connection, tables);
			session.setNewRowInitializer(row -> {
				row.put("CREATED_AT", LocalDateTime.now());
			});
			session.setPreparedStatementBeforeExecuteHandler(statement -> {
				System.out.println(statement);
			});
			System.out.println("---------------------------COPY------------------------------------");
			JdbcTreeDataCopySession copySession = new JdbcTreeDataCopySession(source, session);
			initializer.accept(copySession);
			try (copySession) {
				while (copySession.next(tab)) {
					Row sourceRow = copySession.getRow(tab);
					Row row = copySession.newCopy(sourceRow, tabTo);
					while (copySession.next(tab1)) {
						sourceRow = copySession.getRow(tab1);
						row = copySession.newCopy(sourceRow, tab1To);
						while (copySession.next(tab1_1)) {
							sourceRow = copySession.getRow(tab1_1);
							row = copySession.newCopy(sourceRow, tab1_1To);
							//
							row = copySession.newRow(tab1_1_1To);
							row.put("ROW_NO", 1);
							row.put("TXT", sourceRow.get("TXT1"));
							row = copySession.newRow(tab1_1_1To);
							row.put("ROW_NO", 2);
							row.put("TXT", sourceRow.get("TXT2"));
							row = copySession.newRow(tab1_1_1To);
							row.put("ROW_NO", 3);
							row.put("TXT", sourceRow.get("TXT3"));
						}
					}
				}
			}
			tab.read(connection);
			tab1.read(connection);
			tab1_1.read(connection);
			tabTo.read(connection);
			tab1To.read(connection);
			tab1_1To.read(connection);
			tab1_1_1To.read(connection);
			assertEquals(0, tab.getRows().size());
			assertEquals(rowSize1, tabTo.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(rowSize1 * rowSize2, tab1To.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(rowSize1 * rowSize2 * rowSize3, tab1_1To.getRows().size());
			assertEquals(rowSize1 * rowSize2 * rowSize3 * 3, tab1_1_1To.getRows().size());
		}, (connection) -> {
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
			this.dropTables(connection, "TAB_1_1_1_TO");
			this.dropTables(connection, "TAB_1_1_TO");
			this.dropTables(connection, "TAB_1_TO");
			this.dropTables(connection, "TAB_TO");
		});
	}

	@Test
	void testCopyAndNormalizeHierarchicalData1() throws SQLException {
		testCopyAndNormalizeHierarchicalData(3, 4, 5, copySession -> {

		});
	}

	@Test
	void testCopyAndNormalizeHierarchicalData2() throws SQLException {
		testCopyAndNormalizeHierarchicalData(3, 4, 5, copySession -> {
			copySession.setRootBatchSize(2);
		});
	}

	@Test
	void testCopyAndNormalizeHierarchicalData3() throws SQLException {
		testCopyAndNormalizeHierarchicalData(10, 4, 5, copySession -> {
			copySession.setRootBatchSize(2);
			copySession.setHoldCursorStrategy(HoldCursorStrategy.HOLD);
		});
		testCopyAndNormalizeHierarchicalData(10, 4, 5, copySession -> {
			copySession.setRootBatchSize(2);
			copySession.setHoldCursorStrategy(HoldCursorStrategy.REOPEN);
		});
	}

	private JdbcTreeDataSession createDate(Connection connection, List<Table> tables, int rowSize1, int rowSize2,
			int rowSize3) throws SQLException {
		int cnt = 0;
		final Table tab = tables.get(cnt++);
		final Table tab1 = tables.get(cnt++);
		final Table tab1_1 = tables.get(cnt++);
		JdbcTreeDataSession session = new JdbcTreeDataSession(connection, tables);
		session.setNewRowInitializer(row -> {
			row.put("CREATED_AT", LocalDateTime.now());
		});
		session.setBeforeRootBatchHandler((batchCounter, table, rows) -> {
			System.out.println("BeforeRootBatch batchCount=" + batchCounter);
			rows.forEach(row -> System.out.println(row));
			assertTrue(session.getRootBatchSize() >= table.getRows().size());
		});
		session.setPreparedStatementBeforeExecuteHandler(statement -> {
			System.out.println(statement);
		});
		System.out.println("---------------------------INSERT------------------------------------");
		session.setTableOperationMode(TableOperationMode.INSERT);
		try (session) {
			for (int i = 0; i < rowSize1; i++) {
				Table current = tab;
				Row row = session.newRow(current);
				row.put("PK_COL1", current.getName() + "_PK_COL1_" + i);
				row.put("PK_COL2", current.getName() + "_PK_COL2_" + i);
				row.put("TXT", current.getName() + "_TXT_" + i);
				for (int j = 0; j < rowSize2; j++) {
					current = tab1;
					row = session.newRow(current);
					row.put("PK_COL3", current.getName() + "_PK_COL3_" + j);
					row.put("TXT", current.getName() + "_TXT_" + j);
					for (int k = 0; k < rowSize3; k++) {
						current = tab1_1;
						row = session.newRow(current);
						row.put("PK_COL4A", current.getName() + "_PK_COL4A_" + k);
						row.put("TXT1", current.getName() + "_TXT1_" + k);
						row.put("TXT2", current.getName() + "_TXT2_" + k);
						row.put("TXT3", current.getName() + "_TXT3_" + k);
					}
				}
			}
		}
		session.close();
		session.setTableOperationMode(TableOperationMode.NONE);
		session.select(tab);
		session.select(tab1);
		session.select(tab1_1);
		return session;
	}

	private void test(SQLExceptionConsumer<Connection> cons, SQLExceptionConsumer<Connection> finCons)
			throws SQLException {
		try (HikariDataSource ds = newInternalDataSource(); Connection conn = ds.getConnection();) {
			cons.accept(conn);
			finCons.accept(conn);
		}
	}

}
