/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.command.jdbc.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.test.AbstractDbCommandTest;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.data.schemas.function.SQLExceptionConsumer;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession.TableOperationMode;
import com.sqlapp.util.CommonUtils;
import com.zaxxer.hikari.HikariDataSource;

class JdbcTreeDataSessionIdentitySelectUpdateInsert extends AbstractDbCommandTest {

	private String CREATE_TABLE = """
			CREATE TABLE TAB
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
			)""";
	private String CREATE_TABLE_1 = """
			CREATE TABLE TAB_1
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 4 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_1_1 = """
			CREATE TABLE TAB_1_1
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 5 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_1(ID)
			)""";
	private String CREATE_TABLE_2 = """
			CREATE TABLE TAB_2
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 7 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_2_1 = """
			CREATE TABLE TAB_2_1
			(
				    ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 11 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  , TXT VARCHAR(256)
				  , CREATED_AT DATETIME NOT NULL
				, FOREIGN KEY(PARENT_ID) REFERENCES TAB_2(ID)
			)""";

	/**
	 * Register data from multiple tables in a hierarchical structure using JDBC
	 * batch inserts, while automatically managing the hierarchy and setting foreign
	 * keys.
	 * 
	 * @throws SQLException
	 */
	@Test
	void testInsertUpdateWithGeneratedKey() throws SQLException {
		test(connection -> {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
			executeSql(connection, CREATE_TABLE);
			executeSql(connection, CREATE_TABLE_1);
			executeSql(connection, CREATE_TABLE_1_1);
			executeSql(connection, CREATE_TABLE_2);
			executeSql(connection, CREATE_TABLE_2_1);
			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
			assertTrue(schemaOption.isPresent());
			Schema schema = schemaOption.get();
			JdbcTreeDataSession session = new JdbcTreeDataSession(connection, schema.getTables());
			session.setNewRowInitializer(row -> {
				row.put("CREATED_AT", LocalDateTime.now());
			});
			session.setSqlHandler((t, sqlType, sql) -> {
				System.out.println("table=" + t.getName() + ", sqlType=" + sqlType);
				System.out.println(sql);
				return sql;
			});
			session.setPreparedStatementBeforeExecuteHandler(statement -> {
				System.out.println(statement);
			});
			session.setRootBatchSize(3);
			session.setCommitEveryRoots(2);
			boolean[] hasRootBatchSizeRows = new boolean[1];
			hasRootBatchSizeRows[0] = false;
			long[] batchCounterHolder = new long[1];
			long[] commitCounterHolder = new long[1];
			session.setBeforeRootBatchHandler((batchCounter, table, rows) -> {
				System.out.println("BeforeRootBatch batchCount=" + batchCounter);
				rows.forEach(row -> System.out.println(row));
				assertTrue(session.getRootBatchSize() >= table.getRows().size());
			});
			session.setAfterRootBatchHandler((batchCounter, table, rows) -> {
				System.out.println("AfterRootBatch batchCount=" + batchCounter);
				rows.forEach(row -> System.out.println(row));
				assertTrue(session.getRootBatchSize() >= rows.size());
				if (session.getRootBatchSize() == rows.size()) {
					hasRootBatchSizeRows[0] = true;
				}
				batchCounterHolder[0] = batchCounter;
			});
			session.setBeforeCommitEveryRootsHandler((commitCounter, row) -> {
				System.out.println("BeforeCommitEveryRoots commitCount=" + commitCounter);
				commitCounterHolder[0] = commitCounter;
			});
			session.setAfterCommitEveryRootsHandler((commitCounter, row) -> {
				System.out.println("AfterCommitEveryRoots commitCount=" + commitCounter + ", lastRow=" + row);
				commitCounterHolder[0] = commitCounter;
			});
			final Table tab = schema.getTables().get("TAB");
			final Table tab1 = schema.getTables().get("TAB_1");
			final Table tab1_1 = schema.getTables().get("TAB_1_1");
			final Table tab2 = schema.getTables().get("TAB_2");
			final Table tab2_1 = schema.getTables().get("TAB_2_1");
			System.out.println("---------------------------INSERT------------------------------------");
			session.setTableOperationMode(TableOperationMode.INSERT);
			int loop = 3;
			try (session) {
				for (int i = 0; i < loop; i++) {
					Table current = tab;
					Row row = session.newRow(current);
					row.put("TXT", current.getName() + "_TXT_" + i);// If the number of calls to this method in the root
																	// hierarchy exceeds the rootBatchSize, automatic
																	// JDBC
																	// batch processing will occur.
					for (int j = 0; j < 2; j++) {
						current = tab1;
						row = session.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j);
						for (int k = 0; k < 3; k++) {
							current = tab1_1;
							row = session.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("TXT", current.getName() + "_TXT_" + k);
						}
					}
					for (int j = 0; j < 4; j++) {
						current = tab2;
						row = session.newRow(current); // <- PARENT_ID are inherited automatically.(Generated Identity)
						row.put("TXT", current.getName() + "_TXT_" + j);
						for (int k = 0; k < 2; k++) {
							current = tab2_1;
							row = session.newRow(current); // <- PARENT_ID are inherited automatically.(Generated
															// Identity)
							row.put("TXT", current.getName() + "_TXT_" + k);
						}
					}
				}
			}
			assertEquals(0, tab.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(0, tab2.getRows().size());
			assertEquals(0, tab2_1.getRows().size());
			assertEquals(1, batchCounterHolder[0]);
			assertEquals(1, commitCounterHolder[0]);
			assertTrue(hasRootBatchSizeRows[0]);
			Table table = tab;
			table.read(connection);
			int i = 0;
			assertEquals(loop, table.getRows().size());
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + i, row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				i++;
			}
			table = tab1;
			table.read(connection);
			assertEquals(6, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab1_1;
			table.read(connection);
			assertEquals(18, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 3), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab1.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2;
			table.read(connection);
			assertEquals(12, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 4), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2_1;
			table.read(connection);
			assertEquals(24, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab2.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			System.out.println("---------------------------SELECT------------------------------------");
			tab.getRows().clear();
			tab1.getRows().clear();
			tab1_1.getRows().clear();
			tab2.getRows().clear();
			tab2_1.getRows().clear();
			batchCounterHolder[0] = 0;
			commitCounterHolder[0] = 0;
			Set<Integer> tabPks = CommonUtils.set();
			session.setTableOperationMode(TableOperationMode.NONE);
			try (session) {
				session.select(tab);
				session.select(tab1);
				session.select(tab1_1);
				session.select(tab2);
				session.select(tab2_1);
				i = 0;
				while (session.next(tab)) {
					Row row = session.getRow(tab);
					Integer id = row.get("ID");
					if (tabPks.contains(id)) {
						assertTrue(false, "id=" + id);
					}
					tabPks.add(id);
					println(row);
					while (session.next(tab1)) {
						Row row1 = session.getRow(tab1);
						println(row1);
						while (session.next(tab1_1)) {
							Row row1_1 = session.getRow(tab1_1);
							println(row1_1);
						}
					}
					while (session.next(tab2)) {
						Row row2 = session.getRow(tab2);
						println(row2);
						while (session.next(tab2_1)) {
							Row row2_1 = session.getRow(tab2_1);
							println(row2_1);
						}
					}
				}
			}
			assertEquals(0, tab.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(0, tab2.getRows().size());
			assertEquals(0, tab2_1.getRows().size());
//			assertEquals(2, batchCounterHolder[0]);
			assertEquals(0, commitCounterHolder[0]);
			assertTrue(hasRootBatchSizeRows[0]);
			//
			System.out.println(
					"---------------------------SELECT AND INSERT AND UPDATE------------------------------------");
			tab.getRows().clear();
			tab1.getRows().clear();
			tab1_1.getRows().clear();
			tab2.getRows().clear();
			tab2_1.getRows().clear();
			batchCounterHolder[0] = 0;
			commitCounterHolder[0] = 0;
			session.setTableOperationMode(TableOperationMode.NONE);
			try (session) {
				session.select(tab);
				session.select(tab1);
				session.select(tab1_1);
				session.select(tab2);
				session.select(tab2_1);
				i = 0;
				while (session.next(tab)) {
					Row row = session.getRow(tab);
					// On the first call to next(tab):
					// 1. Fetch up to rootBatchSize rows from TAB.
					// 2. Load all selected child tables (TAB1, TAB1_1, TAB2, TAB2_1)
					// associated with the fetched root rows.
					// Subsequent calls only advance the current root row.
					println(row);
					int j = 0;
					while (session.next(tab1)) {
						Row row1 = session.getRow(tab1);
						row1.put("TXT", row1.get("TXT") + "_UPDATED");
						row1.update(); // UPDATE
						println(row1);
						int k = 0;
						while (session.next(tab1_1)) {
							Row row1_1 = session.getRow(tab1_1);
							println(row1_1);
							k++;
						}
						Row row1_1 = session.newRow(tab1_1);
						row1_1.put("TXT", tab1_1.getName() + "_TXT_INSERT_" + j);
						row1_1.insert(); // INSERT
						j++;
					}
					while (session.next(tab2)) {
						Row row2 = session.getRow(tab2);
						println(row2);
						while (session.next(tab2_1)) {
							Row row2_1 = session.getRow(tab2_1);
							println(row2_1);
						}
					}
					i++;
				}
			}
			assertEquals(0, tab.getRows().size());
			assertEquals(0, tab1.getRows().size());
			assertEquals(0, tab1_1.getRows().size());
			assertEquals(0, tab2.getRows().size());
			assertEquals(0, tab2_1.getRows().size());
//			assertEquals(2, batchCounterHolder[0]);
			assertEquals(0, commitCounterHolder[0]);
			assertTrue(hasRootBatchSizeRows[0]);
			table = tab;
			table.read(connection);
			i = 0;
			assertEquals(loop, table.getRows().size());
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + i, row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				i++;
			}
			table = tab1;
			table.read(connection);
			assertEquals(6, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2) + "_UPDATED", row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab1_1;
			table.read(connection);
			assertEquals(24, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				if (i < 18) {
					assertEquals(table.getName() + "_TXT_" + (i % 3), row.get("TXT"));
				} else {
					assertEquals(table.getName() + "_TXT_INSERT_" + (i % 2), row.get("TXT"));
				}
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab1.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2;
			table.read(connection);
			assertEquals(12, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 4), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
			table = tab2_1;
			table.read(connection);
			assertEquals(24, table.getRows().size());
			i = 0;
			for (Row row : table.getRows()) {
				System.out.println(table.getName() + ", row=" + row);
				assertEquals(table.getName() + "_TXT_" + (i % 2), row.get("TXT"));
				assertNotNull(row.get("CREATED_AT"));
				Row parentRow = tab2.getRows().find(r -> {
					return Objects.equals(r.get("ID"), row.get("PARENT_ID"));
				});
				assertEquals((int) parentRow.get("ID"), (int) row.get("PARENT_ID"));
				i++;
			}
		}, (connection) -> {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
		});
	}

	private void println(Row row) {
		System.out.println("Table[name=" + row.getTable().getName() + ", row=" + row + "]");
	}

	private void test(SQLExceptionConsumer<Connection> cons, SQLExceptionConsumer<Connection> finCons)
			throws SQLException {
		try (HikariDataSource ds = newInternalDataSource(); Connection conn = ds.getConnection();) {
			cons.accept(conn);
			finCons.accept(conn);
		}
	}

}
