/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.oracle;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.sql.Connection;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.oracle.OracleContainer;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkInsertResolver;
import com.sqlapp.jdbc.bulk.BulkOption;

/** Exercises Oracle JDBC batching against Oracle Database 23ai Free. */
class OracleBulkInsertTest {
	private static final OracleContainer ORACLE = ReusableTestcontainers.configure(
			new OracleContainer("gvenzl/oracle-free:23-slim-faststart"));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(ORACLE);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(ORACLE);
	}

	@Test
	void insertsBatchesAndSupportsIdentitySelection() throws Exception {
		try (Connection connection = ORACLE.createConnection("");
				var statement = connection.createStatement()) {
			try {
				statement.execute("DROP TABLE SQLAPP_BULK_ORACLE PURGE");
			} catch (java.sql.SQLException ignored) {
				// The isolated test database can start without the table.
			}
			statement.execute("CREATE TABLE SQLAPP_BULK_ORACLE ("
					+ "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
					+ "TXT VARCHAR2(200), NULLABLE_VALUE VARCHAR2(20), PAYLOAD RAW(20))");
			final Table generated = createTable();
			generated.getRows().add(row -> {
				row.put("TXT", "日本語\nline");
				row.put("NULLABLE_VALUE", null);
				row.put("PAYLOAD", new byte[] { 0, (byte) 0xff });
			});
			assertEquals(1, BulkInsertResolver.execute(connection, generated,
					BulkOption.builder().batchSize(2).build()));

			final Table explicit = createTable();
			explicit.getRows().add(row -> {
				row.put("ID", 42);
				row.put("TXT", "explicit");
				row.put("PAYLOAD", new byte[] { 1 });
			});
			assertEquals(1, BulkInsertResolver.execute(connection, explicit,
					BulkOption.builder().keepIdentity(true).build()));

			try (var resultSet = statement.executeQuery("SELECT ID, TXT, "
					+ "NULLABLE_VALUE, PAYLOAD FROM SQLAPP_BULK_ORACLE ORDER BY ID")) {
				resultSet.next();
				assertEquals(1, resultSet.getInt("ID"));
				assertEquals("日本語\nline", resultSet.getString("TXT"));
				assertNull(resultSet.getString("NULLABLE_VALUE"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff }, resultSet.getBytes("PAYLOAD"));
				resultSet.next();
				assertEquals(42, resultSet.getInt("ID"));
			}
		}
	}

	private static Table createTable() {
		final Table table = new Table("SQLAPP_BULK_ORACLE");
		table.getColumns().add(new Column("ID").setDataType(DataType.DECIMAL)
				.setIdentity(true));
		table.getColumns().add(new Column("TXT").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("NULLABLE_VALUE").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("PAYLOAD").setDataType(DataType.VARBINARY));
		return table;
	}
}
