/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.oracle;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.math.BigDecimal;
import java.sql.Connection;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.oracle.OracleContainer;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.db.dialect.test.BulkMigrationTransactionAssertions;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkOption;
import com.sqlapp.jdbc.bulk.BulkUpsertOption;
import com.sqlapp.jdbc.bulk.BulkUpsertResolver;

/** Exercises JDBC staging and MERGE against Oracle Database 23ai Free. */
class OracleBulkUpsertTest {
	private static final OracleContainer ORACLE = ReusableTestcontainers.configure(
			new OracleContainer("gvenzl/oracle-free:23-slim-faststart"));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(ORACLE);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(ORACLE);
	}

	@Test
	void databaseCheckpointRejectsTransactionBreakingStaging() throws Exception {
		try (Connection connection = ORACLE.createConnection("");
				var statement = connection.createStatement()) {
			try { statement.execute("DROP TABLE SQLAPP_CHUNK_MIGRATION_ORACLE"); }
			catch (java.sql.SQLException ignored) { }
			statement.execute("CREATE TABLE SQLAPP_CHUNK_MIGRATION_ORACLE "
					+ "(CODE VARCHAR2(20) PRIMARY KEY, NAME VARCHAR2(100))");
			final Table table = new Table("SQLAPP_CHUNK_MIGRATION_ORACLE");
			final Column code = new Column("CODE").setDataType(DataType.VARCHAR).setLength(20);
			table.getColumns().add(code);
			table.getColumns().add(new Column("NAME").setDataType(DataType.VARCHAR).setLength(100));
			table.setPrimaryKey("PK_SQLAPP_CHUNK_MIGRATION_ORACLE", code);
			BulkMigrationTransactionAssertions.assertDatabaseCheckpointRejected(connection,
					table, "CODE", "NAME", "SELECT COUNT(*) FROM SQLAPP_CHUNK_MIGRATION_ORACLE");
		}
	}

	@Test
	void updatesMatchesAndInsertsMissingRowsThroughBatchStaging()
			throws Exception {
		try (Connection connection = ORACLE.createConnection("");
				var statement = connection.createStatement()) {
			statement.execute("CREATE TABLE SQLAPP_BULK_UPSERT_ORACLE ("
					+ "ID NUMBER GENERATED BY DEFAULT AS IDENTITY UNIQUE, "
					+ "CODE VARCHAR2(20) PRIMARY KEY, NAME NVARCHAR2(100), "
					+ "AMOUNT NUMBER(12,2), PAYLOAD RAW(20))");
			statement.execute("INSERT INTO SQLAPP_BULK_UPSERT_ORACLE "
					+ "(CODE, NAME, AMOUNT, PAYLOAD) VALUES "
					+ "('A', 'old', 1.00, HEXTORAW('01'))");

			final Table table = createTable();
			table.getRows().add(row -> {
				row.put("CODE", "A");
				row.put("NAME", "更新後\nline");
				row.put("AMOUNT", new BigDecimal("12.34"));
				row.put("PAYLOAD", new byte[] { 0, (byte) 0xff });
			});
			table.getRows().add(row -> {
				row.put("CODE", "B");
				row.put("NAME", null);
				row.put("AMOUNT", null);
			});
			table.getRows().add(row -> {
				row.put("CODE", "C");
				row.put("NAME", "");
				row.put("AMOUNT", new BigDecimal("0.00"));
				row.put("PAYLOAD", new byte[] { 2 });
			});

			assertEquals(3, BulkUpsertResolver.execute(connection, table,
					BulkUpsertOption.builder().bulkOption(
							BulkOption.builder().batchSize(2).build()).build()));

			try (var resultSet = statement.executeQuery("SELECT ID, CODE, NAME, "
					+ "AMOUNT, PAYLOAD FROM SQLAPP_BULK_UPSERT_ORACLE ORDER BY CODE")) {
				resultSet.next();
				assertEquals(1L, resultSet.getLong("ID"));
				assertEquals("A", resultSet.getString("CODE"));
				assertEquals("更新後\nline", resultSet.getString("NAME"));
				assertEquals(new BigDecimal("12.34"),
						resultSet.getBigDecimal("AMOUNT"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff },
						resultSet.getBytes("PAYLOAD"));
				resultSet.next();
				assertEquals("B", resultSet.getString("CODE"));
				assertNull(resultSet.getString("NAME"));
				assertNull(resultSet.getBigDecimal("AMOUNT"));
				resultSet.next();
				assertEquals("C", resultSet.getString("CODE"));
				// Oracle stores an empty string as NULL.
				assertNull(resultSet.getString("NAME"));
				assertArrayEquals(new byte[] { 2 }, resultSet.getBytes("PAYLOAD"));
			}
		}
	}

	private static Table createTable() {
		final Table table = new Table("SQLAPP_BULK_UPSERT_ORACLE");
		final Column id = new Column("ID").setDataType(DataType.DECIMAL)
				.setIdentity(true);
		final Column code = new Column("CODE").setDataType(DataType.VARCHAR)
				.setLength(20).setNotNull(true);
		table.getColumns().add(id);
		table.getColumns().add(code);
		table.getColumns().add(new Column("NAME").setDataType(DataType.NVARCHAR)
				.setLength(100));
		table.getColumns().add(new Column("AMOUNT").setDataType(DataType.DECIMAL)
				.setLength(12).setScale(2));
		table.getColumns().add(new Column("PAYLOAD")
				.setDataType(DataType.VARBINARY).setLength(20));
		table.setPrimaryKey("PK_SQLAPP_BULK_UPSERT_ORACLE", code);
		return table;
	}
}
