/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-h2.
 */
package com.sqlapp.data.db.dialect.h2.metadata;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.sql.SqlType;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Domain;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.Sequence;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.util.CommonUtils;

/**
 * H2 2.x catalog metadata round trip.
 */
class H2MetadataRoundTripTest {

	@Test
	void testDomainTableAndColumnRoundTrip() throws Exception {
		try (Connection connection = DriverManager.getConnection(
				"jdbc:h2:mem:metadata-round-trip;DB_CLOSE_DELAY=-1");
				Statement statement = connection.createStatement()) {
			statement.execute("""
					CREATE DOMAIN POSITIVE_AMOUNT AS DECIMAL(18,2)
					DEFAULT 0 CHECK (VALUE >= 0)
					""");
			statement.execute(
					"COMMENT ON DOMAIN POSITIVE_AMOUNT IS 'Positive amount'");
			statement.execute("""
					CREATE SEQUENCE ORDER_SEQ START WITH 50
					INCREMENT BY 5 MINVALUE 5 MAXVALUE 1000
					CYCLE CACHE 20
					""");
			statement.execute(
					"CREATE TABLE PARENT_TABLE (ID BIGINT PRIMARY KEY)");
			statement.execute("""
					CREATE TABLE METADATA_ROUND_TRIP
					(
						  ID BIGINT GENERATED BY DEFAULT AS IDENTITY
						    (START WITH 100 INCREMENT BY 10) PRIMARY KEY
						, NAME VARCHAR(100) DEFAULT 'unknown' NOT NULL
						, AMOUNT POSITIVE_AMOUNT
						, DOUBLE_AMOUNT DECIMAL(18,2)
						    GENERATED ALWAYS AS (AMOUNT * 2)
						, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
						    ON UPDATE CURRENT_TIMESTAMP
						, PARENT_ID BIGINT
						, CONSTRAINT CK_METADATA_NAME CHECK (NAME <> '')
						, CONSTRAINT FK_METADATA_PARENT FOREIGN KEY (PARENT_ID)
						    REFERENCES PARENT_TABLE(ID)
					)
					""");
			statement.execute("""
					CREATE INDEX IDX_METADATA_NAME
					ON METADATA_ROUND_TRIP(NAME DESC)
					""");
			statement.execute("""
					CREATE VIEW METADATA_VIEW AS
					SELECT ID, NAME FROM METADATA_ROUND_TRIP
					""");
			statement.execute(
					"COMMENT ON TABLE METADATA_ROUND_TRIP IS 'Round trip table'");
			statement.execute(
					"COMMENT ON COLUMN METADATA_ROUND_TRIP.NAME IS 'Display name'");

			final var dialect = DialectResolver.getInstance()
					.getDialect(connection);
			final var reader = dialect.getCatalogReader()
					.getSchemaReader();
			reader.setSchemaName("PUBLIC");
			final Schema schema = CommonUtils.first(
					reader.getAllFull(connection));

			final Domain domain = schema.getDomains()
					.get("POSITIVE_AMOUNT");
			assertNotNull(domain);
			assertEquals("Positive amount", domain.getRemarks());
			assertEquals("0", domain.getDefaultValue());
			assertTrue(domain.getCheck().contains("VALUE >= 0"),
					domain.getCheck());

			final Sequence sequence = schema.getSequences()
					.get("ORDER_SEQ");
			assertNotNull(sequence);
			assertEquals(50, sequence.getStartValue().intValue());
			assertEquals(5, sequence.getIncrementBy().intValue());
			assertEquals(5, sequence.getMinValue().intValue());
			assertEquals(1000, sequence.getMaxValue().intValue());
			assertEquals(20, sequence.getCacheSize());
			assertTrue(sequence.isCycle());

			final Table table = schema.getTables()
					.get("METADATA_ROUND_TRIP");
			assertNotNull(table);
			assertEquals("Round trip table", table.getRemarks());
			assertNotNull(table.getIndexes().get("IDX_METADATA_NAME"));
			assertNotNull(table.getConstraints()
					.get("CK_METADATA_NAME"));
			assertNotNull(table.getConstraints()
					.get("FK_METADATA_PARENT"));
			assertNotNull(schema.getViews().get("METADATA_VIEW"));

			final Column id = table.getColumns().get("ID");
			assertTrue(id.isIdentity());
			assertEquals(100L, id.getIdentityStartValue());
			assertEquals(10L, id.getIdentityStep());

			final Column name = table.getColumns().get("NAME");
			assertTrue(name.isNotNull());
			assertEquals("'unknown'", name.getDefaultValue());
			assertEquals("Display name", name.getRemarks());

			final Column amount = table.getColumns().get("AMOUNT");
			assertNotNull(amount.getDataTypeName());

			final Column generated = table.getColumns()
					.get("DOUBLE_AMOUNT");
			assertNotNull(generated.getFormula());
			assertTrue(generated.getFormula().contains("AMOUNT"),
					generated.getFormula());

			final Column updatedAt = table.getColumns()
					.get("UPDATED_AT");
			assertNotNull(updatedAt.getOnUpdate());
			assertTrue(updatedAt.getOnUpdate()
					.contains("CURRENT_TIMESTAMP"),
					updatedAt.getOnUpdate());

			final String regenerated = dialect
					.createSqlFactoryRegistry()
					.createSql(table, SqlType.CREATE).get(0)
					.getSqlText();
			assertTrue(regenerated.contains("METADATA_ROUND_TRIP"),
					regenerated);
			assertTrue(regenerated.contains("DOUBLE_AMOUNT"),
					regenerated);
		}
	}
}
