/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.command.migration.assessment;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import com.sqlapp.exceptions.CommandException;
import io.github.spannm.jackcess.Database;
import io.github.spannm.jackcess.DatabaseBuilder;

class AssessDatabaseMigrationCommandTest {
	@TempDir Path directory;

	@Test
	void generatesRoundTrippableMappingTemplatesForBothTargets() throws Exception {
		final var command = command("template.accdb", "oracle", "19c");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			new io.github.spannm.jackcess.TableBuilder("Orders")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("ID", io.github.spannm.jackcess.DataType.LONG).withAutoNumber(true))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("Enabled", io.github.spannm.jackcess.DataType.BOOLEAN))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("Name", io.github.spannm.jackcess.DataType.TEXT).withLengthInUnits(80))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("Amount", io.github.spannm.jackcess.DataType.NUMERIC).withPrecision(12).withScale(2))
					.toTable(database);
		}
		final Path template = directory.resolve("target-template.yaml");
		command.setMappingTemplateFile(template.toFile());
		command.setFailOnBlockers(false);
		command.run();
		String yaml = Files.readString(template);
		assertTrue(yaml.contains("sourceFingerprint: \"" + command.getReport().sourceFingerprint() + "\""));
		assertTrue(yaml.contains("targetDatabase: \"oracle\""));
		assertTrue(yaml.contains("targetType: \"NUMBER(1,0)\""));
		assertTrue(yaml.contains("targetType: \"VARCHAR2(80 CHAR)\""));
		assertTrue(yaml.contains("targetType: \"NUMBER(12,2)\""));
		assertTrue(yaml.contains("identity: true"));
		command.setMappingTemplateFile(null);
		command.setMappingFile(template.toFile());
		command.setMappingTemplateFile(template.toFile());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("mappingTemplateFile"));
		command.setMappingTemplateFile(null);
		command.run();
		assertEquals(3, command.getReport().formatVersion());
		assertEquals(4, command.getReport().targetMapping().tables().getFirst().columns().size());
		final Path ddl = directory.resolve("target.sql");
		command.setDdlOutputFile(ddl.toFile());
		command.run();
		String sql = Files.readString(ddl);
		assertTrue(sql.startsWith("-- sqlapp sourceFingerprint: " + command.getReport().sourceFingerprint() + "\n"
				+ "-- sqlapp mappingFingerprint: " + command.getReport().mappingFingerprint() + "\n"
				+ "-- sqlapp target: oracle 19c\n"));
		assertTrue(sql.contains("CREATE TABLE \"Orders\""));
		assertTrue(sql.contains("\"Enabled\" NUMBER(1,0) NULL"));
		assertTrue(sql.contains("\"ID\" NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY"));
		assertTrue(sql.contains("Nullable unique keys, source defaults, conversion expressions and cascade rules are not included"));

		command.setMappingFile(null);
		command.setDdlOutputFile(null);
		command.setTargetDatabase("sqlserver");
		command.setTargetVersion("2022");
		command.setMappingTemplateFile(template.toFile());
		command.run();
		yaml = Files.readString(template);
		assertTrue(yaml.contains("targetDatabase: \"sqlserver\""));
		assertTrue(yaml.contains("targetType: \"bit\""));
		assertTrue(yaml.contains("targetType: \"nvarchar(80)\""));
		assertTrue(yaml.contains("targetType: \"decimal(12,2)\""));
		command.setMappingTemplateFile(null);
		command.setMappingFile(template.toFile());
		command.setDdlOutputFile(ddl.toFile());
		command.run();
		sql = Files.readString(ddl);
		assertTrue(sql.startsWith("-- sqlapp sourceFingerprint: " + command.getReport().sourceFingerprint() + "\n"
				+ "-- sqlapp mappingFingerprint: " + command.getReport().mappingFingerprint() + "\n"
				+ "-- sqlapp target: sqlserver 2022\n"));
		assertTrue(sql.contains("CREATE TABLE [Orders]"));
		assertTrue(sql.contains("[Enabled] bit NULL"));
		assertTrue(sql.contains("[ID] int IDENTITY(1,1)"));
		assertTrue(sql.contains("\nGO\n"));
		command.setDdlOutputFile(template.toFile());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("ddlOutputFile"));
	}

	@Test
	void targetDdlRequiresAMapping() throws Exception {
		final var command = command("ddl.accdb", "oracle", "19c");
		command.setDdlOutputFile(directory.resolve("target.sql").toFile());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("requires mappingFile"));
	}

	@Test
	void resolvesFingerprintBoundMappingAndValidatesObservedOracleCapacity() throws Exception {
		final var command = command("mapping.accdb", "oracle", "19c");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			final var table = new io.github.spannm.jackcess.TableBuilder("顧客")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("名前", io.github.spannm.jackcess.DataType.TEXT))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("金額", io.github.spannm.jackcess.DataType.NUMERIC).withPrecision(10).withScale(2))
					.toTable(database);
			table.addRow("長い名前", new java.math.BigDecimal("123.45"));
			table.addRow(null, null);
		}
		final String fingerprint = AssessMigrationCommand.fingerprint(command.getInputFile());
		final Path mapping = directory.resolve("mapping.yaml");
		Files.writeString(mapping, ("""
				format: sqlapp-database-migration-mapping
				version: 1
				sourceFingerprint: %s
				targetDatabase: oracle
				targetVersion: 19c
				tables:
				  - sourceTable: 顧客
				    targetSchema: APP
				    targetTable: CUSTOMERS
				    checkExpressions:
				      - "NAME IS NOT NULL"
				    columns:
				      - sourceColumn: 名前
				        targetColumn: NAME
				        targetType: VARCHAR2(2 CHAR)
				        nullable: false
				        defaultExpression: "'unknown'"
				        conversion: preserve Unicode text
				      - sourceColumn: 金額
				        targetColumn: AMOUNT
				        targetType: NUMBER(4,2)
				""").formatted(fingerprint));
		command.setMappingFile(mapping.toFile());
		command.setHtmlOutputFile(directory.resolve("mapping.html").toFile());
		command.setScanData(true);
		assertThrows(CommandException.class, command::run);
		assertEquals(3, command.getReport().formatVersion());
		assertEquals("oracle", command.getReport().targetMapping().targetDatabase());
		assertEquals("顧客", command.getReport().targetMapping().tables().getFirst().sourceTable().name());
		assertEquals("CUSTOMERS", command.getReport().targetMapping().tables().getFirst().targetTable());
		assertEquals(List.of("NAME IS NOT NULL"), command.getReport().targetMapping().tables().getFirst().checkExpressions());
		assertEquals("'unknown'", command.getReport().targetMapping().tables().getFirst().columns().getFirst().defaultExpression());
		assertEquals(AssessMigrationCommand.fingerprint(mapping.toFile()), command.getReport().mappingFingerprint());
		assertTrue(command.getReport().assessment().findings().stream().anyMatch(f -> f.ruleId().equals("access.oracle.mapping.observed-text-overflow")));
		assertTrue(command.getReport().assessment().findings().stream().anyMatch(f -> f.ruleId().equals("access.oracle.mapping.observed-number-overflow")));
		assertTrue(command.getReport().assessment().findings().stream().anyMatch(f -> f.ruleId().equals("access.oracle.mapping.observed-null")));
		final String json = Files.readString(command.getOutputFile().toPath());
		assertTrue(json.contains("mappingFingerprint"));
		assertTrue(json.contains("targetMapping"));
		final String html = Files.readString(command.getHtmlOutputFile().toPath());
		assertTrue(html.contains("Resolved target mapping"));
		assertTrue(html.contains("Target checks:</strong> NAME IS NOT NULL"));

		Files.writeString(mapping, Files.readString(mapping).replace(fingerprint, "wrong"));
		assertThrows(CommandException.class, command::run);
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		assertNull(command.getReport());
		Files.writeString(mapping, Files.readString(mapping).replace("wrong", fingerprint) + "unknownTypo: true\n");
		assertThrows(CommandException.class, command::run);
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		Files.writeString(mapping, Files.readString(mapping).replace("unknownTypo: true\n", "")
				.replace("defaultExpression: \"'unknown'\"", "defaultExpression: \"0; DROP TABLE X\""));
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("defaultExpression"));
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		Files.writeString(mapping, Files.readString(mapping)
				.replace("defaultExpression: \"0; DROP TABLE X\"", "identity: true\n        defaultExpression: \"0\""));
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("cannot be combined"));
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		Files.writeString(mapping, Files.readString(mapping)
				.replace("identity: true\n        defaultExpression: \"0\"", "defaultExpression: \"0\"")
				.replace("NAME IS NOT NULL", "NAME IS NOT NULL; DROP TABLE CUSTOMERS"));
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("checkExpressions"));
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		Files.writeString(mapping, Files.readString(mapping)
				.replace("NAME IS NOT NULL; DROP TABLE CUSTOMERS", "NAME IS NOT NULL")
				.replace("targetTable: CUSTOMERS", "targetTable: \"CUSTOMERS\\nARCHIVE\""));
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("targetTable"));
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
	}

	@Test
	void reportsTablesAndColumnsOmittedFromAnOtherwiseValidMapping() throws Exception {
		final var command = command("partial-mapping.accdb", "oracle", "19c");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			new io.github.spannm.jackcess.TableBuilder("Mapped")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("Included", io.github.spannm.jackcess.DataType.LONG))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("Omitted", io.github.spannm.jackcess.DataType.TEXT))
					.toTable(database);
			new io.github.spannm.jackcess.TableBuilder("OmittedTable")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("ID", io.github.spannm.jackcess.DataType.LONG))
					.toTable(database);
		}
		final Path mapping = directory.resolve("partial-mapping.yaml");
		Files.writeString(mapping, ("""
				format: sqlapp-database-migration-mapping
				version: 1
				sourceFingerprint: %s
				targetDatabase: oracle
				targetVersion: 19c
				tables:
				  - sourceTable: Mapped
				    columns:
				      - sourceColumn: Included
				        targetType: NUMBER(10,0)
				""").formatted(AssessMigrationCommand.fingerprint(command.getInputFile())));
		command.setMappingFile(mapping.toFile());
		command.run();
		assertEquals("REVIEW_REQUIRED", command.getReport().status());
		assertTrue(command.getReport().assessment().findings().stream().anyMatch(f ->
				f.ruleId().equals("migration.mapping.unmapped-table") && f.object().name().equals("OmittedTable")));
		assertTrue(command.getReport().assessment().findings().stream().anyMatch(f ->
				f.ruleId().equals("migration.mapping.unmapped-column") && f.object().name().equals("Omitted")));
		assertEquals(1, command.getReport().assessment().inventory().stream()
				.filter(i -> i.type().equals("unmappedTables")).findFirst().orElseThrow().count());
		assertEquals(1, command.getReport().assessment().inventory().stream()
				.filter(i -> i.type().equals("unmappedColumnsInMappedTables")).findFirst().orElseThrow().count());
		assertFalse(command.getReport().assessment().findings().stream().anyMatch(f ->
				f.ruleId().equals("migration.mapping.unmapped-column") && f.object().table().equals("OmittedTable")));
	}

	@Test
	void writesOptionalHtmlReviewAtomicallyAndRejectsPathCollisions() throws Exception {
		final var command = command("html.accdb", "oracle", "19c");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			new io.github.spannm.jackcess.TableBuilder("T")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("C", io.github.spannm.jackcess.DataType.TEXT))
					.toTable(database);
		}
		final var html = directory.resolve("assessment.html").toFile();
		command.setHtmlOutputFile(html);
		command.setFailOnBlockers(false);
		command.run();
		final String text = Files.readString(html.toPath());
		assertTrue(text.startsWith("<!doctype html>"));
		assertTrue(text.contains("Database migration assessment"));
		assertTrue(text.contains("Oracle 19c"));
		assertTrue(Files.readString(command.getOutputFile().toPath()).startsWith("{"));

		command.setHtmlOutputFile(command.getOutputFile());
		final String json = Files.readString(command.getOutputFile().toPath());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("distinct"));
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		command.setHtmlOutputFile(command.getInputFile());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("distinct"));
	}

	@Test
	void publishesOrphanBlockersAndStructuredCountsForBothTargets() throws Exception {
		final var command = command("orphan.accdb", "oracle", "19c");
		final var html = directory.resolve("orphan.html").toFile();
		command.setHtmlOutputFile(html);
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			final var parent = new io.github.spannm.jackcess.TableBuilder("Parent")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("ID", io.github.spannm.jackcess.DataType.LONG)).toTable(database);
			final var child = new io.github.spannm.jackcess.TableBuilder("Child")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("PID", io.github.spannm.jackcess.DataType.LONG)).toTable(database);
			new io.github.spannm.jackcess.RelationshipBuilder(parent, child).addColumns("ID", "PID").withName("FK_child").toRelationship(database);
			child.addRow(123);
		}
		command.run();
		assertEquals("REVIEW_REQUIRED", command.getReport().status());
		command.setScanData(true);
		for (final String target : new String[] { "oracle", "sqlserver" }) {
			command.setTargetDatabase(target);
			command.setTargetVersion(target.equals("oracle") ? "19c" : "2022");
			assertThrows(CommandException.class, command::run);
			assertEquals("BLOCKED", command.getReport().status());
			assertTrue(Files.readString(html.toPath()).contains("access.data.orphan-key"));
			assertEquals(1L, command.getReport().dataProfile().integrityChecks().getFirst().violationRows());
			final var json = Files.readString(command.getOutputFile().toPath());
			assertTrue(json.contains("integrityChecks"));
			assertTrue(json.contains("access.data.orphan-key"));
		}
		command.setFailOnBlockers(false);
		command.run();
		assertEquals("BLOCKED", command.getReport().status());
	}

	@Test
	void optInScanWritesVersionedAggregatesAndPublishesObservedOracleBlocker() throws Exception {
		final var command = command("scan.accdb", "oracle", "19c");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			final var table = new io.github.spannm.jackcess.TableBuilder("T")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("C", io.github.spannm.jackcess.DataType.TEXT)
							.withProperty(io.github.spannm.jackcess.PropertyMap.ALLOW_ZERO_LEN_PROP, true)
							.withProperty(io.github.spannm.jackcess.PropertyMap.REQUIRED_PROP, true))
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("D", io.github.spannm.jackcess.DataType.SHORT_DATE_TIME))
					.toTable(database);
			table.addRow("", java.time.LocalDateTime.of(1600, 1, 1, 0, 0));
			table.addRow("private-text", java.time.LocalDateTime.of(2026, 1, 1, 0, 0));
		}
		final byte[] before = Files.readAllBytes(command.getInputFile().toPath());
		assertFalse(command.isScanData());
		command.run();
		assertEquals(1, command.getReport().formatVersion());
		assertNull(command.getReport().dataProfile());
		assertFalse(Files.readString(command.getOutputFile().toPath()).contains("dataProfile"));
		command.setScanData(true);
		assertThrows(CommandException.class, command::run);
		assertEquals("BLOCKED", command.getReport().status());
		assertEquals(2, command.getReport().formatVersion());
		assertTrue(command.getReport().dataScanned());
		assertEquals(2, command.getReport().dataProfile().tables().getFirst().rowCount());
		final var json = Files.readString(command.getOutputFile().toPath());
		assertTrue(json.contains("observed-empty-string"));
		assertTrue(json.contains("maximumUtf8Bytes"));
		assertFalse(json.contains("private-text"));
		assertFalse(json.contains("access.data-not-scanned"));
		command.setFailOnBlockers(false);
		command.run();
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
		command.setTargetDatabase("sqlserver");
		command.setTargetVersion("2022");
		command.setFailOnBlockers(true);
		command.run();
		assertEquals("REVIEW_REQUIRED", command.getReport().status());
		assertTrue(command.getReport().assessment().findings().stream()
				.anyMatch(f -> f.ruleId().equals("access.sqlserver.observed-legacy-datetime-range")));
		assertArrayEquals(before, Files.readAllBytes(command.getInputFile().toPath()));
	}

	@Test
	void scanOptionCannotBeIgnoredByLegacyProviders() throws Exception {
		final var command = command("input.assessment-fixture", "fixture", "1");
		Files.writeString(command.getOutputFile().toPath(), "previous");
		command.setScanData(true);
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("scanData is not supported"));
		assertNull(command.getReport());
		assertEquals("previous", Files.readString(command.getOutputFile().toPath()));
	}

	@Test
	void sqlServerReportComposesAccessCoverageAndPreservesTheFile() throws Exception {
		final var command = command("sqlserver.accdb", "sqlserver", "2022");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) {
			new io.github.spannm.jackcess.TableBuilder("顧客")
					.addColumn(new io.github.spannm.jackcess.ColumnBuilder("名前", io.github.spannm.jackcess.DataType.TEXT))
					.toTable(database).addRow("非公開データ");
			database.createLinkedTable("外部", directory.resolve("missing.accdb").toString(), "T");
		}
		final byte[] before = Files.readAllBytes(command.getInputFile().toPath());
		command.run();
		assertEquals("Microsoft SQL Server", command.getReport().targetProduct());
		assertFalse(command.getReport().dataScanned());
		assertFalse(command.getReport().relationshipsCollected());
		final var json = Files.readString(command.getOutputFile().toPath());
		assertTrue(json.contains("access.sqlserver.type"));
		assertTrue(json.contains("access.linked-table"));
		assertTrue(json.contains("access.application-coverage"));
		assertFalse(json.contains("access.oracle."));
		assertFalse(json.contains("非公開データ"));
		assertArrayEquals(before, Files.readAllBytes(command.getInputFile().toPath()));
		command.setTargetVersion("2025");
		assertThrows(CommandException.class, command::run);
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
	}

	private AssessDatabaseMigrationCommand command(String file, String target, String version) throws Exception {
		final var command = new AssessDatabaseMigrationCommand();
		command.setInputFile(Files.writeString(directory.resolve(file), "fixture").toFile());
		command.setOutputFile(directory.resolve("report.json").toFile());
		command.setTargetDatabase(target);
		command.setTargetVersion(version);
		return command;
	}

	@Test
	void composesIndependentProvidersPreservingSourceBlockersAndNativeDetails() throws Exception {
		final var command = command("input.assessment-fixture", "fixture", "1");
		assertThrows(CommandException.class, command::run);
		assertEquals("Fixture Source", command.getReport().sourceProduct());
		assertEquals("Fixture Target", command.getReport().targetProduct());
		assertEquals("BLOCKED", command.getReport().status());
		final var json = Files.readString(command.getOutputFile().toPath());
		assertTrue(json.contains("fixture.source-blocker"));
		assertTrue(json.contains("fixture.target-review"));
		assertTrue(json.contains("preserved"));
		command.setFailOnBlockers(false);
		command.run();
		assertEquals(json, Files.readString(command.getOutputFile().toPath()));
	}

	@Test
	void rejectsMissingTargetAndUnsupportedSourceTargetAndVersionWithoutReplacingReport() throws Exception {
		final var command = command("input.assessment-fixture", "fixture", "1");
		Files.writeString(command.getOutputFile().toPath(), "previous");
		for (String database : new String[] { null, "", "oracle", "postgres" }) {
			command.setTargetDatabase(database);
			assertThrows(CommandException.class, command::run);
			assertNull(command.getReport());
			assertEquals("previous", Files.readString(command.getOutputFile().toPath()));
		}
		command.setTargetDatabase("fixture");
		command.setTargetVersion("unknown");
		assertThrows(CommandException.class, command::run);
		command.setInputFile(Files.writeString(directory.resolve("unsupported.xyz"), "fixture").toFile());
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("source provider"));
	}

	@Test
	void genericAndCompatibilityEntryPointsProduceEquivalentAccessReports() throws Exception {
		final var command = command("source.accdb", "ORACLE", "19C");
		Files.delete(command.getInputFile().toPath());
		try (var database = DatabaseBuilder.create(Database.FileFormat.V2010, command.getInputFile())) { }
		command.run();
		final var generic = command.getReport();
		assertEquals("Oracle", generic.targetProduct());
		assertEquals("19c", generic.targetVersion());
		final var alias = new AssessAccessOracleMigrationCommand();
		alias.setInputFile(command.getInputFile());
		alias.setOutputFile(command.getOutputFile());
		alias.setTargetVersion("19c");
		alias.run();
		assertEquals(generic, alias.getReport());
		assertThrows(IllegalArgumentException.class, () -> alias.setTargetDatabase("postgres"));
		command.setTargetDatabase("postgres");
		command.setTargetVersion("16");
		assertTrue(assertThrows(CommandException.class, command::run).getMessage().contains("found 0"));
	}
}
