CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_no VARCHAR(30) NOT NULL,
    customer_id BIGINT NOT NULL,
    order_date DATE NOT NULL,
    order_status VARCHAR(20) NOT NULL
    , CONSTRAINT pk_orders PRIMARY KEY (order_id)
    , CONSTRAINT uk_orders_1 UNIQUE (order_no)
    , CONSTRAINT fk_orders_customer
        FOREIGN KEY(customer_id)
        REFERENCES customers(customer_id)
);