CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_code VARCHAR(20) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    closing_day INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
   , CONSTRAINT pk_customers PRIMARY KEY (customer_id)
   , CONSTRAINT uk_customers_1 UNIQUE (customer_code)
);