/**
 * Copyright (C) 2026-2026 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-command.
 *
 * sqlapp-command is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-command is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-command.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.data.db.command.generator;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.SQLException;
import java.time.YearMonth;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.generator.GenerateDataInsertCommand.RowMonitor;
import com.sqlapp.data.db.command.generator.config.TableGeneratorConfig;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.sql.node.SqlNode;
import com.sqlapp.util.CommonUtils;
import com.zaxxer.hikari.HikariDataSource;

class GenerateDataConfigAndInsertCommandTest3 extends AbstractGeneratorCommandTest {

	@Test
	void testGenerationInsertBatch2() {
		final int dmlBatchSize = 2;
		final int iterate = 100;
		test(command -> {
			command.setQueryCommitInterval(3);
			command.setDmlBatchSize(dmlBatchSize);
			command.setGeneratorConfigConsumer(config -> {
				config.setDataSourceExpression("iterator(" + iterate + ")");
			});
			int[] handleCount = new int[1];
			long[] exptectedUpdatedRowCount = new long[1];
			RowMonitor rowMonitor = new RowMonitor(createRowMonitor()) {
				@Override
				public void handle(final TableGeneratorConfig tableConfig, final Map<String, Object> resultSetValueMap,
						long readRowCount, long dataSourceRowNumber, long generatedCount, long updatedRowCount,
						Map<String, Object> covertedColumnMapping, Map<String, Object> generatedValue,
						final Table startTable, final Table table, final List<SqlNode> insertSqlNodes) {
					this.internal.handle(tableConfig, resultSetValueMap, readRowCount, dataSourceRowNumber,
							generatedCount, updatedRowCount, covertedColumnMapping, generatedValue, startTable, table,
							insertSqlNodes);
				}
			};
			command.setRowMonitor(rowMonitor);
		});
	}

	private RowMonitor createRowMonitor() {
		RowMonitor rowMonitor = new RowMonitor() {
			@Override
			public void handle(final TableGeneratorConfig tableConfig, final Map<String, Object> resultSetValueMap,
					long readRowCount, long dataSourceRowNumber, long generatedCount, long updatedRowCount,
					Map<String, Object> covertedColumnMapping, Map<String, Object> generatedValue,
					final Table startTable, final Table table, final List<SqlNode> insertSqlNodes) {
				System.out.println("=====================================");
				System.out.println("tableConfig.name=" + tableConfig.getName());
				System.out.println("resultSetValueMap=" + resultSetValueMap);
				System.out.println("readRowCount=" + readRowCount + ", dataSourceRowNumber=" + dataSourceRowNumber
						+ ", generatedCount=" + generatedCount + ", updatedRowCount=" + updatedRowCount
						+ ", insertSqlNodes.size=" + insertSqlNodes.size());
				System.out.println("covertedColumnMapping=" + covertedColumnMapping);
				Map<String, Object> map = CommonUtils.linkedMap(generatedValue);
				map.remove("_min");
				map.remove("_max");
				System.out.println("generatedValue=" + map);
			}
		};
		return rowMonitor;
	}

	private final String CREATE_TABLE = """
			CREATE TABLE TAB_TYPE
			(
				ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
				, YM VARCHAR(6) NOT NULL
				, QUANTITY DECIMAL(15,2) NOT NULL
			)
			""";

	private void test(Consumer<GenerateDataConfigAndInsertCommand> cons) {
		HikariDataSource ds = newInternalDataSource();
		try {
			GenerateDataConfigAndInsertCommand command = new GenerateDataConfigAndInsertCommand();
			command.setDataSource(ds);
			// command.setOutputDirectory(new File("./"));
			command.setIncludeTables("TAB_TYPE");
			command.setCloseDataSource(false);
			command.setCommitLogEnabled(true);
			command.setOutputDirectory(testProjectDir);
			this.executeSql(command, CREATE_TABLE);
			cons.accept(command);
			command.run();
			Table table = new Table("TAB_TYPE");
			table.setSchemaName("PUBLIC");
			table.read(ds.getConnection());
			long i = 0;
			YearMonth yearMonth = YearMonth.of(2000, 1);
			for (Row row : table.getRows()) {
				assertEquals(i, (Long) row.get("ID"));
				String exprectedYm = yearMonth.plusMonths(i).toString().replace("-", "");
				assertEquals(exprectedYm, row.get("YM"));
				System.out.println("i=" + i + ", " + row);
				i++;
			}
			dropTables(command, "TAB_TYPE");
		} catch (SQLException e) {
			throw new RuntimeException(e);
		} finally {
			ds.close();
		}
	}

}
