/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.saphana;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.Duration;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkInsertResolver;
import com.sqlapp.jdbc.bulk.BulkOption;

/** Exercises JDBC batch bulk insertion against SAP HANA Express 2.0. */
class SapHanaBulkInsertTest {
	private static final String PASSWORD = "HxeTest9xA";
	private static final Path PASSWORD_DIRECTORY = createPasswordDirectory();
	private static final GenericContainer<?> HANA = ReusableTestcontainers.configure(
			new GenericContainer<>(DockerImageName.parse(
					"saplabs/hanaexpress:2.00.088.00.20251110.1"))
					.withFileSystemBind(PASSWORD_DIRECTORY.toString(),
							"/hana/mounts", BindMode.READ_WRITE)
					.withCommand("--passwords-url",
							"file:///hana/mounts/password.json",
							"--agree-to-sap-license", "--dont-check-system")
					.withExposedPorts(39041)
					.withCreateContainerCmdModifier(command -> command
							.withHostName("hxehost").getHostConfig()
							.withShmSize(1L << 30))
					.waitingFor(Wait.forLogMessage(".*Startup finished.*", 1)
							.withStartupTimeout(Duration.ofMinutes(30))));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(HANA);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(HANA);
	}

	@Test
	void insertsBatchesAndGeneratedByDefaultIdentity() throws Exception {
		try (Connection connection = createConnection();
				var statement = connection.createStatement()) {
			try {
				statement.execute("DROP SCHEMA SQLAPP_BULK CASCADE");
			} catch (java.sql.SQLException ignored) {
				// The isolated test database can start without the schema.
			}
			statement.execute("CREATE SCHEMA SQLAPP_BULK");
			statement.execute("CREATE COLUMN TABLE SQLAPP_BULK.BULK_ROWS ("
					+ "ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
					+ "TXT NVARCHAR(200), NULLABLE_VALUE NVARCHAR(20), "
					+ "EMPTY_VALUE NVARCHAR(20), PAYLOAD VARBINARY(20))");

			final Table generated = createTable();
			generated.getRows().add(row -> {
				row.put("TXT", "日本語\nline");
				row.put("NULLABLE_VALUE", null);
				row.put("EMPTY_VALUE", "");
				row.put("PAYLOAD", new byte[] { 0, (byte) 0xff });
			});
			generated.getRows().add(row -> row.put("TXT", "second"));
			generated.getRows().add(row -> row.put("TXT", "third"));
			assertEquals(3, BulkInsertResolver.execute(connection, generated,
					BulkOption.builder().batchSize(2).build()));

			final Table explicit = createTable();
			explicit.getRows().add(row -> {
				row.put("ID", 42L);
				row.put("TXT", "explicit");
				row.put("EMPTY_VALUE", "");
				row.put("PAYLOAD", new byte[] { 1 });
			});
			assertEquals(1, BulkInsertResolver.execute(connection, explicit,
					BulkOption.builder().keepIdentity(true).build()));

			try (var resultSet = statement.executeQuery("SELECT ID, TXT, "
					+ "NULLABLE_VALUE, EMPTY_VALUE, PAYLOAD "
					+ "FROM SQLAPP_BULK.BULK_ROWS ORDER BY ID")) {
				resultSet.next();
				assertEquals(1L, resultSet.getLong("ID"));
				assertEquals("日本語\nline", resultSet.getString("TXT"));
				assertNull(resultSet.getString("NULLABLE_VALUE"));
				assertEquals("", resultSet.getString("EMPTY_VALUE"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff },
						resultSet.getBytes("PAYLOAD"));
				resultSet.next();
				assertEquals(2L, resultSet.getLong("ID"));
				resultSet.next();
				assertEquals(3L, resultSet.getLong("ID"));
				resultSet.next();
				assertEquals(42L, resultSet.getLong("ID"));
			}
		}
	}

	private static Table createTable() {
		final Table table = new Table("BULK_ROWS").setSchemaName("SQLAPP_BULK");
		table.getColumns().add(new Column("ID").setDataType(DataType.BIGINT)
				.setIdentity(true));
		table.getColumns().add(new Column("TXT").setDataType(DataType.NVARCHAR));
		table.getColumns().add(new Column("NULLABLE_VALUE")
				.setDataType(DataType.NVARCHAR));
		table.getColumns().add(new Column("EMPTY_VALUE")
				.setDataType(DataType.NVARCHAR));
		table.getColumns().add(new Column("PAYLOAD")
				.setDataType(DataType.VARBINARY));
		return table;
	}

	private static Connection createConnection() throws Exception {
		final String url = "jdbc:sap://localhost:" + HANA.getMappedPort(39041)
				+ "/?databaseName=HXE";
		return DriverManager.getConnection(url, "SYSTEM", PASSWORD);
	}

	private static Path createPasswordDirectory() {
		try {
			final Path directory = Files.createTempDirectory("sqlapp-hana-bulk-");
			Files.writeString(directory.resolve("password.json"),
					"{\"master_password\":\"" + PASSWORD + "\"}",
					StandardCharsets.UTF_8);
			return directory;
		} catch (Exception e) {
			throw new ExceptionInInitializerError(e);
		}
	}
}
