/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.postgres;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.math.BigDecimal;
import java.sql.Connection;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.postgresql.PostgreSQLContainer;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkInsertResolver;
import com.sqlapp.jdbc.bulk.BulkOption;

/** Exercises PostgreSQL JDBC CopyManager against PostgreSQL 18. */
class PostgresBulkInsertTest {
	private static final PostgreSQLContainer POSTGRES =
			ReusableTestcontainers.configure(new PostgreSQLContainer("postgres:18.4"));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(POSTGRES);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(POSTGRES);
	}

	@Test
	void copiesRowsWithIdentityTextNullEmptyBinaryAndArray() throws Exception {
		try (Connection connection = POSTGRES.createConnection("");
				var statement = connection.createStatement()) {
			statement.execute("CREATE SCHEMA bulk_test");
			statement.execute("""
					CREATE TABLE bulk_test.copy_target (
					  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					  name TEXT NOT NULL,
					  nullable_value TEXT,
					  empty_value TEXT,
					  amount NUMERIC(12,2),
					  payload BYTEA,
					  tags TEXT[]
					)
					""");
			final Table table = createTable("copy_target");
			table.getRows().add(row -> {
				row.put("name", "a,\"quoted\"\nline");
				row.put("nullable_value", null);
				row.put("empty_value", "");
				row.put("amount", new BigDecimal("123.45"));
				row.put("payload", new byte[] { 0, (byte) 0xff });
				row.put("tags", new String[] { "one", "two,three" });
			});

			assertEquals(1, BulkInsertResolver.execute(connection, table,
					BulkOption.defaults()));
			try (var resultSet = statement.executeQuery(
					"SELECT * FROM bulk_test.copy_target")) {
				resultSet.next();
				assertEquals(1L, resultSet.getLong("id"));
				assertEquals("a,\"quoted\"\nline", resultSet.getString("name"));
				assertNull(resultSet.getString("nullable_value"));
				assertEquals("", resultSet.getString("empty_value"));
				assertEquals(new BigDecimal("123.45"), resultSet.getBigDecimal("amount"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff }, resultSet.getBytes("payload"));
				assertArrayEquals(new String[] { "one", "two,three" },
						(String[]) resultSet.getArray("tags").getArray());
			}
		}
	}

	@Test
	void preservesExplicitIdentityWhenRequested() throws Exception {
		try (Connection connection = POSTGRES.createConnection("");
				var statement = connection.createStatement()) {
			statement.execute("CREATE SCHEMA bulk_identity_test");
			statement.execute("CREATE TABLE bulk_identity_test.copy_target (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT, nullable_value TEXT, empty_value TEXT, amount NUMERIC(12,2), payload BYTEA, tags TEXT[])");
			final Table table = createTable("copy_target");
			table.setSchemaName("bulk_identity_test");
			table.getRows().add(row -> {
				row.put("id", 100L);
				row.put("name", "explicit");
			});

			assertEquals(1, BulkInsertResolver.execute(connection, table,
					BulkOption.builder().keepIdentity(true).build()));
			try (var resultSet = statement.executeQuery(
					"SELECT id, name FROM bulk_identity_test.copy_target")) {
				resultSet.next();
				assertEquals(100L, resultSet.getLong("id"));
				assertEquals("explicit", resultSet.getString("name"));
			}
		}
	}

	private Table createTable(final String name) {
		final Table table = new Table(name);
		table.setSchemaName("bulk_test");
		table.getColumns().add(new Column("id").setDataType(DataType.BIGINT)
				.setIdentity(true));
		table.getColumns().add(new Column("name").setDataType(DataType.LONGVARCHAR));
		table.getColumns().add(new Column("nullable_value").setDataType(DataType.LONGVARCHAR));
		table.getColumns().add(new Column("empty_value").setDataType(DataType.LONGVARCHAR));
		table.getColumns().add(new Column("amount").setDataType(DataType.DECIMAL)
				.setLength(12).setScale(2));
		table.getColumns().add(new Column("payload").setDataType(DataType.VARBINARY));
		table.getColumns().add(new Column("tags").setDataType(DataType.ARRAY));
		return table;
	}
}
