/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.postgres;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.sql.Connection;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.postgresql.PostgreSQLContainer;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.db.dialect.test.FailingTransactionalCheckpointStore;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkUpsertOption;
import com.sqlapp.jdbc.bulk.BulkUpsertResolver;
import com.sqlapp.jdbc.bulk.ChunkedBulkMigrationExecutor;
import com.sqlapp.jdbc.bulk.ChunkedBulkMigrationOption;
import com.sqlapp.jdbc.bulk.JdbcBulkMigrationCheckpointStore;

/** Exercises COPY staging and ON CONFLICT against PostgreSQL 18. */
class PostgresBulkUpsertTest {
	private static final PostgreSQLContainer POSTGRES =
			ReusableTestcontainers.configure(new PostgreSQLContainer("postgres:18.4"));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(POSTGRES);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(POSTGRES);
	}

	@Test
	void updatesMatchesAndInsertsMissingRowsThroughCopyStaging()
			throws Exception {
		try (Connection connection = POSTGRES.createConnection("");
				var statement = connection.createStatement()) {
			statement.execute("CREATE SCHEMA bulk_upsert_test");
			statement.execute("""
					CREATE TABLE bulk_upsert_test.target (
					  id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
					  code TEXT PRIMARY KEY,
					  name TEXT,
					  amount NUMERIC(12,2),
					  payload BYTEA,
					  tags TEXT[]
					)
					""");
			statement.execute("""
					INSERT INTO bulk_upsert_test.target
					  (code, name, amount, payload, tags)
					VALUES ('A', 'old', 1.00, '\\x01', ARRAY['old'])
					""");

			final Table table = createTable();
			table.getRows().add(row -> {
				row.put("code", "A");
				row.put("name", "更新後\nline");
				row.put("amount", new BigDecimal("12.34"));
				row.put("payload", new byte[] { 0, (byte) 0xff });
				row.put("tags", new String[] { "one", "two,three" });
			});
			table.getRows().add(row -> {
				row.put("code", "B");
				row.put("name", null);
				row.put("amount", null);
			});
			table.getRows().add(row -> {
				row.put("code", "C");
				row.put("name", "");
				row.put("amount", new BigDecimal("0.00"));
				row.put("payload", new byte[] { 2 });
			});

			assertEquals(3, BulkUpsertResolver.execute(connection, table,
					BulkUpsertOption.defaults()));

			try (var resultSet = statement.executeQuery("SELECT id, code, name, "
					+ "amount, payload, tags FROM bulk_upsert_test.target "
					+ "ORDER BY code")) {
				resultSet.next();
				assertEquals(1L, resultSet.getLong("id"));
				assertEquals("A", resultSet.getString("code"));
				assertEquals("更新後\nline", resultSet.getString("name"));
				assertEquals(new BigDecimal("12.34"),
						resultSet.getBigDecimal("amount"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff },
						resultSet.getBytes("payload"));
				assertArrayEquals(new String[] { "one", "two,three" },
						(String[]) resultSet.getArray("tags").getArray());
				resultSet.next();
				assertEquals("B", resultSet.getString("code"));
				assertNull(resultSet.getString("name"));
				assertNull(resultSet.getBigDecimal("amount"));
				resultSet.next();
				assertEquals("C", resultSet.getString("code"));
				assertEquals("", resultSet.getString("name"));
				assertArrayEquals(new byte[] { 2 }, resultSet.getBytes("payload"));
			}
		}
	}

	@Test
	void resumesWithDatabaseCheckpointInTheTargetTransaction() throws Exception {
		try (Connection connection = POSTGRES.createConnection("");
				var statement = connection.createStatement()) {
			statement.execute("DROP TABLE IF EXISTS public.chunk_migration_target");
			statement.execute("CREATE TABLE public.chunk_migration_target "
					+ "(code TEXT PRIMARY KEY, name TEXT)");
			final Table table = new Table("chunk_migration_target").setSchemaName("public");
			final Column code = new Column("code").setDataType(DataType.LONGVARCHAR)
					.setNotNull(true);
			table.getColumns().add(code);
			table.getColumns().add(new Column("name").setDataType(DataType.LONGVARCHAR));
			table.setPrimaryKey("chunk_migration_target_pkey", code);
			for (int i = 1; i <= 3; i++) {
				final int value = i;
				table.getRows().add(row -> {
					row.put("code", "C" + value);
					row.put("name", "name-" + value);
				});
			}
			final String migrationId = "postgres-" + java.util.UUID.randomUUID();
			final var option = ChunkedBulkMigrationOption.builder()
					.migrationId(migrationId).chunkSize(2).build();
			final var checkpointStore = new JdbcBulkMigrationCheckpointStore(connection,
					option.getCheckpointTableName());
			assertThrows(java.sql.SQLException.class,
					() -> ChunkedBulkMigrationExecutor.execute(connection, table, option,
							new FailingTransactionalCheckpointStore(connection, checkpointStore)));
			assertEquals(0, scalar(statement,
					"SELECT COUNT(*) FROM public.chunk_migration_target"));
			assertTrue(checkpointStore.load(migrationId).isEmpty());

			final var result = ChunkedBulkMigrationExecutor.execute(connection, table, option);
			assertEquals(3, result.getProcessedRows());
			assertEquals(2, result.getCompletedChunks());
			assertEquals(3, scalar(statement,
					"SELECT COUNT(*) FROM public.chunk_migration_target"));
			assertEquals(3, new JdbcBulkMigrationCheckpointStore(connection,
					option.getCheckpointTableName()).load(migrationId).orElseThrow().getProcessedRows());
		}
	}

	private static int scalar(final java.sql.Statement statement, final String sql)
			throws java.sql.SQLException {
		try (var resultSet = statement.executeQuery(sql)) {
			resultSet.next();
			return resultSet.getInt(1);
		}
	}

	private static Table createTable() {
		final Table table = new Table("target").setSchemaName("bulk_upsert_test");
		final Column id = new Column("id").setDataType(DataType.BIGINT)
				.setIdentity(true);
		final Column code = new Column("code").setDataType(DataType.LONGVARCHAR)
				.setNotNull(true);
		table.getColumns().add(id);
		table.getColumns().add(code);
		table.getColumns().add(new Column("name").setDataType(DataType.LONGVARCHAR));
		table.getColumns().add(new Column("amount").setDataType(DataType.DECIMAL)
				.setLength(12).setScale(2));
		table.getColumns().add(new Column("payload").setDataType(DataType.VARBINARY));
		table.getColumns().add(new Column("tags").setDataType(DataType.ARRAY));
		table.setPrimaryKey("target_pkey", code);
		return table;
	}
}
