/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.postgres;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.postgresql.PostgreSQLContainer;

import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.postgres.Postgres140;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.ForeignKeyConstraint;
import com.sqlapp.data.schemas.PartitioningType;

/** PostgreSQL 14 compatibility coverage for the metadata reader tree. */
class Postgres140MetadataReaderTest {
	private static final PostgreSQLContainer POSTGRES =
			ReusableTestcontainers.configure(new PostgreSQLContainer("postgres:14"));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(POSTGRES);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(POSTGRES);
	}

	@Test
	void testMetadataReaderRemainsOperationalOnPostgres14() throws SQLException {
		try (Connection connection = POSTGRES.createConnection("");
				Statement statement = connection.createStatement()) {
			createObjects(statement);
			var dialect = DialectResolver.getInstance().getDialect(connection);
			assertInstanceOf(Postgres140.class, dialect);
			var reader = dialect.getCatalogReader();
			String catalogName = connection.getCatalog();
			reader.setCatalogName(catalogName);
			var catalog = reader.getAllFull(connection).stream()
					.filter(c -> catalogName.equals(c.getName()))
					.findFirst().orElseThrow();
			var schema = catalog.getSchemas().get("metadata_test_14");
			assertNotNull(schema);
			var child = schema.getTables().get("metadata_child");
			assertNotNull(child);
			var foreignKey = assertInstanceOf(ForeignKeyConstraint.class,
					child.getConstraints().get("fk_metadata_child_parent"));
			assertEquals(2, foreignKey.getColumns().size());
			assertNotNull(child.getIndexes().get("idx_metadata_child_parent"));
			assertNotNull(schema.getSequences().get("metadata_seq"));
			assertNotNull(schema.getViews().get("metadata_view"));
			assertNotNull(schema.getFunctions().get("metadata_function"));
			var partitioned = schema.getTables().get("metadata_events");
			assertNotNull(partitioned);
			assertEquals(PartitioningType.Range,
					partitioned.getPartitioning().getPartitioningType());
			var partition = schema.getTables().get("metadata_events_2025");
			assertNotNull(partition);
			assertEquals("metadata_events",
					partition.getPartitionParent().getTableName());
		}
	}

	private void createObjects(final Statement statement) throws SQLException {
		statement.execute("DROP SCHEMA IF EXISTS metadata_test_14 CASCADE");
		statement.execute("CREATE SCHEMA metadata_test_14");
		statement.execute("CREATE SEQUENCE metadata_test_14.metadata_seq START 10");
		statement.execute("""
				CREATE TABLE metadata_test_14.metadata_events (
				 id bigint NOT NULL, occurred_at date NOT NULL)
				 PARTITION BY RANGE (occurred_at)
				""");
		statement.execute("""
				CREATE TABLE metadata_test_14.metadata_events_2025
				 PARTITION OF metadata_test_14.metadata_events
				 FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')
				""");
		statement.execute("""
				CREATE TABLE metadata_test_14.metadata_parent (
				 id bigint NOT NULL, region char(2) NOT NULL,
				 CONSTRAINT pk_metadata_parent PRIMARY KEY (id, region))
				""");
		statement.execute("""
				CREATE TABLE metadata_test_14.metadata_child (
				 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				 parent_id bigint NOT NULL, parent_region char(2) NOT NULL,
				 amount numeric(18,2) NOT NULL,
				 CONSTRAINT ck_metadata_child_amount CHECK (amount >= 0),
				 CONSTRAINT fk_metadata_child_parent FOREIGN KEY (parent_id, parent_region)
				 REFERENCES metadata_test_14.metadata_parent(id, region))
				""");
		statement.execute("""
				CREATE INDEX idx_metadata_child_parent
				 ON metadata_test_14.metadata_child(parent_id, parent_region)
				""");
		statement.execute("""
				CREATE VIEW metadata_test_14.metadata_view AS
				 SELECT id, amount FROM metadata_test_14.metadata_child
				""");
		statement.execute("""
				CREATE FUNCTION metadata_test_14.metadata_function(p_amount numeric)
				 RETURNS numeric LANGUAGE sql IMMUTABLE AS $$ SELECT p_amount * 2 $$
				""");
	}
}
