/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.oracle.migration;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.regex.Pattern;
import com.sqlapp.data.schemas.migration.assessment.MigrationDataProfile.ColumnProfile;
import com.sqlapp.data.schemas.migration.assessment.ResolvedMigrationTargetMapping;

import com.sqlapp.data.schemas.migration.assessment.DatabaseMigrationAssessmentProvider;
import com.sqlapp.data.schemas.migration.assessment.MigrationAssessment;
import com.sqlapp.data.schemas.migration.assessment.MigrationAssessment.*;
import com.sqlapp.data.schemas.migration.assessment.MigrationAssessmentSource;

/** Oracle logical migration diagnosis. Only Access sources are currently supported. */
public final class OracleDatabaseMigrationAssessmentProvider implements DatabaseMigrationAssessmentProvider {
	@Override
	public String generateTargetDdl(final MigrationAssessmentSource source,
			final ResolvedMigrationTargetMapping mapping, final String targetVersion) {
		return com.sqlapp.data.schemas.migration.assessment.MigrationTargetDdlGenerator
				.generate(source, mapping, OracleDatabaseMigrationAssessmentProvider::oracleName, "\n",
						column -> " GENERATED BY DEFAULT AS IDENTITY", OracleDatabaseMigrationAssessmentProvider::usableObjectName,
						table -> "Preserve Access AutoNumber values with explicit inserts, then verify that the Oracle identity generator starts above the loaded maximum before new inserts.");
	}

	private static String oracleName(final String value) { return "\"" + value.replace("\"", "\"\"") + "\""; }
	private static boolean usableObjectName(final String value) {
		return value.getBytes(java.nio.charset.StandardCharsets.UTF_8).length <= 128
				&& value.codePoints().noneMatch(Character::isISOControl);
	}
	private static final Pattern NUMBER = Pattern.compile("NUMBER(?:\\((\\d+)(?:,(\\d+))?\\))?", Pattern.CASE_INSENSITIVE);
	private static final Pattern TEXT = Pattern.compile("(VARCHAR2|NVARCHAR2|CHAR|NCHAR)\\((\\d+)(?:\\s+(CHAR|BYTE))?\\)", Pattern.CASE_INSENSITIVE);
	private static final Pattern TIMESTAMP = Pattern.compile("TIMESTAMP(?:\\((\\d)\\))?", Pattern.CASE_INSENSITIVE);
	private static final Pattern RAW = Pattern.compile("RAW\\((\\d+)\\)", Pattern.CASE_INSENSITIVE);
	@Override
	public boolean supports(final String sourceProduct, final String targetDatabase, final String targetVersion) {
		return "Microsoft Access".equals(sourceProduct) && "oracle".equalsIgnoreCase(targetDatabase)
				&& AccessOracleMigrationAssessment.supportsTargetVersion(targetVersion);
	}

	@Override
	public String targetProduct() { return "Oracle"; }

	@Override
	public String normalizeTargetVersion(final String version) {
		return AccessOracleMigrationAssessment.validateTargetVersion(version);
	}

	@Override
	public String suggestTargetType(final com.sqlapp.data.schemas.Column column, final String targetVersion) {
		final String type = column.getSpecifics().get("access.sourceType", String.class);
		if (type == null) { return null; }
		return switch (type) {
		case "BOOLEAN" -> "19c".equalsIgnoreCase(targetVersion) || "21c".equalsIgnoreCase(targetVersion) ? "NUMBER(1,0)" : "BOOLEAN";
		case "BYTE" -> "NUMBER(3,0)";
		case "INT" -> "NUMBER(5,0)";
		case "LONG" -> "NUMBER(10,0)";
		case "BIG_INT" -> "NUMBER(19,0)";
		case "MONEY" -> "NUMBER(19,4)";
		case "NUMERIC" -> "NUMBER(" + precision(column, 38) + "," + Math.max(0, column.getScale() == null ? 0 : column.getScale()) + ")";
		case "FLOAT" -> "BINARY_FLOAT";
		case "DOUBLE" -> "BINARY_DOUBLE";
		case "SHORT_DATE_TIME" -> "TIMESTAMP(3)";
		case "EXT_DATE_TIME" -> "TIMESTAMP(9)";
		case "TEXT" -> column.getLength() != null && column.getLength() > 4000 ? "CLOB" : "VARCHAR2(" + length(column, 255, 4000) + " CHAR)";
		case "MEMO" -> "CLOB";
		case "GUID" -> "VARCHAR2(38 CHAR)";
		case "BINARY" -> column.getLength() != null && column.getLength() > 2000 ? "BLOB" : "RAW(" + length(column, 255, 2000) + ")";
		case "OLE" -> "BLOB";
		default -> null;
		};
	}
	private static long length(final com.sqlapp.data.schemas.Column column, final long fallback, final long maximum) {
		return Math.min(maximum, column.getLength() == null || column.getLength() < 1 ? fallback : column.getLength());
	}
	private static long precision(final com.sqlapp.data.schemas.Column column, final long fallback) {
		return Math.min(38, column.getLength() == null || column.getLength() < 1 ? fallback : column.getLength());
	}

	@Override
	public MigrationAssessment assess(final MigrationAssessmentSource source, final String targetVersion) {
		if (!supports(source.sourceProduct(), "oracle", targetVersion)) {
			throw new IllegalArgumentException("Oracle migration assessment supports Access sources and targets 19c, 21c, 23ai, 26ai only");
		}
		final var findings = new ArrayList<Finding>();
		final var inventory = new ArrayList<Inventory>();
		final var profiles = new HashMap<ObjectId, ColumnProfile>();
		if (source.dataProfile() != null) {
			for (final var table : source.dataProfile().tables()) {
				for (final var column : table.columns()) { profiles.put(column.column(), column); }
			}
		}
		for (final var schema : source.schemas()) {
			final var assessment = AccessOracleMigrationAssessment.assess(schema, targetVersion);
			findings.addAll(assessment.findings());
			inventory.addAll(assessment.inventory());
			for (final var table : schema.getTables()) {
				for (final var column : table.getColumns()) {
					final var id = new ObjectId(schema.getCatalogName(), schema.getName(), "column", column.getName(), table.getName());
					final var profile = profiles.get(id);
					// MEMO may be mapped to a LOB, whose empty-value semantics differ from scalar text.
					if (profile != null && "TEXT".equals(profile.sourceType()) && profile.text() != null && profile.text().emptyCount() > 0) {
						findings.add(new Finding("access.oracle.observed-empty-string", column.isNotNull() ? Severity.BLOCKER : Severity.WARNING,
								Evidence.DATABASE, id, profile.text().emptyCount() + " empty strings were observed in a Short Text column.",
								"Choose an explicit representation before scalar Oracle loading; empty strings become NULL and may violate required-column semantics.",
								"https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Nulls.html"));
					}
				}
			}
		}
		findings.add(new Finding("access.oracle.environment", Severity.REVIEW, Evidence.MANUAL_CHECK, null,
				"The Oracle environment and client compatibility were not checked.",
				"Verify exact Oracle release, COMPATIBLE, character sets, identifier lengths/reserved words, collation, privileges and ODBC/JDBC support; rehearse cutover and recovery.", null));
		return new MigrationAssessment(findings, inventory);
	}

	@Override
	public MigrationAssessment assessMapping(final MigrationAssessmentSource source, final String targetVersion,
			final ResolvedMigrationTargetMapping mapping) {
		final var findings = new ArrayList<Finding>();
		final var profiles = profiles(source);
		int columns = 0;
		for (final var table : mapping.tables()) {
			int identities = 0;
			targetIdentifier(findings, table.sourceTable(), "schema", table.targetSchema());
			targetIdentifier(findings, table.sourceTable(), "table", table.targetTable());
			for (final var column : table.columns()) {
				columns++;
				targetIdentifier(findings, column.sourceColumn(), "column", column.targetColumn());
				final String type = column.targetType().trim().replaceAll("\\s+", " ").toUpperCase(Locale.ROOT);
				final var profile = profiles.get(column.sourceColumn());
				if (!supported(type, targetVersion)) {
					findings.add(mappingFinding("type", Severity.BLOCKER, column.sourceColumn(), "Unsupported or invalid Oracle target type: " + column.targetType(),
							"Use an Oracle type supported by this assessment and specify length/precision explicitly."));
					continue;
				}
				if (Boolean.TRUE.equals(column.identity())) {
					identities++;
					if (!oracleIdentityType(type)) {
						findings.add(mappingFinding("identity", Severity.BLOCKER, column.sourceColumn(),
								"Oracle identity generation requires an integer NUMBER target type: " + column.targetType(),
								"Use NUMBER(p,0), or remove identity and define an explicit key generation strategy."));
					}
				}
				nullability(findings, column, profile);
				capacity(findings, column, profile, type);
			}
			if (identities > 1) {
				findings.add(mappingFinding("identity", Severity.BLOCKER, table.sourceTable(),
						"Oracle permits only one identity column per table; mapping contains " + identities + ".",
						"Keep one identity column and define explicit generation for the other columns."));
			}
		}
		findings.add(mappingFinding("coverage", Severity.REVIEW, null,
				"The mapping resolves " + mapping.tables().size() + " tables and " + columns + " columns; conversion expressions were recorded but not executed.",
				"Review unmapped objects, generate and inspect DDL/load transformations, then validate converted values and constraints on Oracle."));
		return new MigrationAssessment(findings, java.util.List.of(new Inventory(null, "", "mappedTables", mapping.tables().size()),
				new Inventory(null, "", "mappedColumns", columns)));
	}

	private static HashMap<ObjectId, ColumnProfile> profiles(final MigrationAssessmentSource source) {
		final var result = new HashMap<ObjectId, ColumnProfile>();
		if (source.dataProfile() != null) { source.dataProfile().tables().forEach(t -> t.columns().forEach(c -> result.put(c.column(), c))); }
		return result;
	}
	private static boolean supported(final String type, final String version) {
		final var number = NUMBER.matcher(type);
		if (number.matches()) {
			if (number.group(1) == null) { return true; }
			final int precision = Integer.parseInt(number.group(1));
			final int scale = number.group(2) == null ? 0 : Integer.parseInt(number.group(2));
			return precision >= 1 && precision <= 38 && scale <= precision;
		}
		final var text = TEXT.matcher(type);
		if (text.matches() && Integer.parseInt(text.group(2)) > 0) { return true; }
		final var timestamp = TIMESTAMP.matcher(type);
		if (timestamp.matches()) { return timestamp.group(1) == null || Integer.parseInt(timestamp.group(1)) <= 9; }
		final var raw = RAW.matcher(type);
		if (raw.matches()) { return Integer.parseInt(raw.group(1)) >= 1 && Integer.parseInt(raw.group(1)) <= 2000; }
		if (java.util.Set.of("CLOB", "NCLOB", "DATE", "BLOB", "BINARY_FLOAT", "BINARY_DOUBLE").contains(type)) { return true; }
		return "BOOLEAN".equals(type) && ("23ai".equals(version) || "26ai".equals(version));
	}
	private static boolean oracleIdentityType(final String type) {
		final var number = NUMBER.matcher(type);
		return number.matches() && (number.group(2) == null || Integer.parseInt(number.group(2)) == 0);
	}
	private static void nullability(final java.util.List<Finding> findings,
			final ResolvedMigrationTargetMapping.ColumnMapping column, final ColumnProfile profile) {
		if (!Boolean.FALSE.equals(column.nullable())) { return; }
		if (profile == null || profile.nullCount() == null) {
			findings.add(mappingFinding("nullability-unverified", Severity.REVIEW, column.sourceColumn(),
					"The target is NOT NULL but source NULL values were not completely scanned.", "Run with scanData=true and resolve excluded column coverage before creating the constraint."));
		} else if (profile.nullCount() > 0) {
			findings.add(mappingFinding("observed-null", Severity.BLOCKER, column.sourceColumn(), profile.nullCount()
					+ " source NULL values do not fit the mapped NOT NULL target.", "Clean or convert these values before loading and creating the constraint."));
		}
	}
	private static void capacity(final java.util.List<Finding> findings,
			final ResolvedMigrationTargetMapping.ColumnMapping column, final ColumnProfile profile, final String type) {
		if (profile == null) { return; }
		final var number = NUMBER.matcher(type);
		if (number.matches() && number.group(1) != null && profile.numeric() != null && profile.numeric().maximumIntegerDigits() != null) {
			final int precision = Integer.parseInt(number.group(1));
			final int scale = number.group(2) == null ? 0 : Integer.parseInt(number.group(2));
			if (profile.numeric().maximumIntegerDigits() > precision - scale || profile.numeric().maximumScale() > scale) {
				findings.add(mappingFinding("observed-number-overflow", Severity.BLOCKER, column.sourceColumn(),
						"Observed numeric digits do not fit " + type + ".", "Increase precision/scale or define and test an explicit rounding/conversion rule."));
			}
		}
		final var text = TEXT.matcher(type);
		if (text.matches() && profile.text() != null) {
			final long limit = Long.parseLong(text.group(2));
			final boolean bytes = "BYTE".equals(text.group(3));
			final Long observed = bytes ? profile.text().maximumUtf8Bytes() : profile.text().maximumCodePoints();
			if (observed != null && observed > limit) {
				findings.add(mappingFinding("observed-text-overflow", Severity.BLOCKER, column.sourceColumn(),
						"Observed text length " + observed + " exceeds mapped " + type + " limit " + limit + ".",
						bytes ? "Choose a larger type and validate against the actual Oracle database character set; UTF-8 is only the reference measurement."
								: "Choose a larger character length or LOB mapping and test client behavior."));
			}
		}
		final var timestamp = TIMESTAMP.matcher(type);
		if (timestamp.matches() && profile.dateTime() != null && profile.dateTime().maximumFractionalDigits() != null) {
			final int precision = timestamp.group(1) == null ? 6 : Integer.parseInt(timestamp.group(1));
			if (profile.dateTime().maximumFractionalDigits() > precision) {
				findings.add(mappingFinding("observed-time-precision", Severity.WARNING, column.sourceColumn(),
						"Observed fractional precision exceeds " + type + ".", "Choose sufficient precision or test and approve rounding."));
			}
		}
	}
	private static Finding mappingFinding(final String rule, final Severity severity, final ObjectId id,
			final String reason, final String action) {
		return new Finding("access.oracle.mapping." + rule, severity, Evidence.DOCUMENTED_RULE, id, reason, action, null);
	}
	private static void targetIdentifier(final java.util.List<Finding> findings, final ObjectId source,
			final String kind, final String name) {
		if (name == null || name.isBlank()) { return; }
		if (name.getBytes(java.nio.charset.StandardCharsets.UTF_8).length > 128) {
			findings.add(mappingFinding("identifier-length", Severity.BLOCKER, source,
					"Mapped target " + kind + " name exceeds 128 UTF-8 bytes: " + name,
					"Choose a shorter name and validate its encoded byte length in the actual Oracle database character set."));
		} else if (!name.matches("[A-Za-z][A-Za-z0-9_$#]*")) {
			findings.add(mappingFinding("identifier", Severity.REVIEW, source,
					"Mapped target " + kind + " name requires quoted-identifier review: " + name,
					"Confirm casing, escaping, reserved words and every application reference."));
		}
	}
}
