package com.sqlapp.data.db.dialect.postgres.sql;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.sql.SqlFactory;
import com.sqlapp.data.db.sql.SqlType;
import com.sqlapp.data.schemas.IdentityGenerationType;
import com.sqlapp.data.schemas.Index;
import com.sqlapp.data.schemas.Table;

class PostgresModernSchemaSqlTest extends AbstractPostgresSqlFactoryTest {
	@Override
	protected int getMajorVersion() {
		return 18;
	}

	@Test
	void testIdentityGeneratedColumnsAndModernIndex() {
		Table table = new Table("ORDERS");
		table.setDialect(dialect);
		table.getColumns().add("ID", c -> c.setDataType(DataType.BIGINT)
				.setIdentity(true).setIdentityGenerationType(IdentityGenerationType.ByDefault));
		table.getColumns().add("PRICE", c -> c.setDataType(DataType.DECIMAL).setLength(18).setScale(2));
		table.getColumns().add("TAXED_PRICE", c -> c.setDataType(DataType.DECIMAL).setLength(18).setScale(2)
				.setFormula("PRICE * 1.1").setFormulaPersisted(false));
		SqlFactory<Table> tableFactory = sqlFactoryRegistry.getSqlFactory(table, SqlType.CREATE);
		String tableSql = tableFactory.createSql(table).get(0).getSqlText()
				.replace("\"", "").replaceAll("\\s+", " ").replace(" )", ")");
		assertTrue(tableSql.contains("ID BIGINT GENERATED BY DEFAULT AS IDENTITY"), tableSql);
		assertTrue(tableSql.contains("GENERATED ALWAYS AS (PRICE * 1.1) VIRTUAL"), tableSql);

		Index index = table.getIndexes().add("UK_ORDERS_PRICE");
		index.setUnique(true);
		index.getColumns().add("PRICE");
		index.getIncludes().add("TAXED_PRICE");
		index.getSpecifics().put(PostgresCreateIndexFactory.NULLS_NOT_DISTINCT, "true");
		SqlFactory<Index> indexFactory = sqlFactoryRegistry.getSqlFactory(index, SqlType.CREATE);
		String indexSql = indexFactory.createSql(index).get(0).getSqlText()
				.replace("\"", "").replaceAll("\\s+", " ").replace(" )", ")");
		assertTrue(indexSql.contains("UNIQUE NULLS NOT DISTINCT INDEX"), indexSql);
		assertTrue(indexSql.contains("INCLUDE"), indexSql);
	}

	@Test
	void testVirtualGeneratedColumnVersionBoundary() {
		Table table = new Table("T");
		table.setDialect(com.sqlapp.data.db.dialect.postgres.DialectHolder.postgreSQL170);
		table.getColumns().add("C", c -> c.setDataType(DataType.INT).setFormula("1").setFormulaPersisted(false));
		SqlFactory<Table> factory = com.sqlapp.data.db.dialect.postgres.DialectHolder.postgreSQL170
				.createSqlFactoryRegistry().getSqlFactory(table, SqlType.CREATE);
		assertThrows(IllegalArgumentException.class, () -> factory.createSql(table));
	}

	@Test
	void testBuiltInRangeAndMultirangeTypes() {
		var postgres13 = com.sqlapp.data.db.dialect.postgres.DialectHolder.postgreSQL130;
		var postgres14 = com.sqlapp.data.db.dialect.postgres.DialectHolder.postgreSQL140;
		var range = new com.sqlapp.data.schemas.Column("ACTIVE_PERIOD");
		var multirange = new com.sqlapp.data.schemas.Column("ACTIVE_PERIODS");

		assertTrue(postgres13.setDbType("daterange", null, null, range));
		assertEquals(DataType.RANGE, range.getDataType());
		assertTrue(postgres14.setDbType("datemultirange", null, null, multirange));
		assertEquals(DataType.MULTIRANGE, multirange.getDataType());

		Table table = new Table("SCHEDULES");
		table.setDialect(postgres14);
		table.getColumns().add(range);
		table.getColumns().add(multirange);
		SqlFactory<Table> factory = postgres14.createSqlFactoryRegistry().getSqlFactory(table, SqlType.CREATE);
		String sql = factory.createSql(table).get(0).getSqlText()
				.replace("\"", "").replaceAll("\\s+", " ").toUpperCase();
		assertTrue(sql.contains("ACTIVE_PERIOD DATERANGE"), sql);
		assertTrue(sql.contains("ACTIVE_PERIODS DATEMULTIRANGE"), sql);
	}
}
