version: '3'

services:
  db:
    build:
      context: ./docker/
    image: h2db
    container_name: sqlitedb
    volumes:
      - ./docker/db/data:/opt/sqlite/data
    ports:
      - 9092:9092
      - 5435:5435
      - 8082:8082
volumes:
  sqlitedb-data:
    driver: local