import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.sqlapp.data.db.command.migration.bulk.BulkMigrationVerificationReportIO;

/** Links the actual artifacts produced by the three repository demos. */
public class DemoOverview {
    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            throw new IllegalArgumentException("Expected the build/docs directory");
        }
        Path docs = Path.of(args[0]);
        for (String file : List.of("offline-demo/index.html", "offline-demo/relationships.html",
                "offline-change/before/index.html", "offline-change/after/index.html",
                "offline-change/change.sql", "offline-migration/execution.json",
                "offline-migration/verification-match.json", "offline-migration/verification-mismatch.json")) {
            if (!Files.isRegularFile(docs.resolve(file))) {
                throw new IllegalStateException("Missing demo artifact: " + file);
            }
        }
        var reports = new BulkMigrationVerificationReportIO();
        var match = reports.read(docs.resolve("offline-migration/verification-match.json"));
        var mismatch = reports.read(docs.resolve("offline-migration/verification-mismatch.json"));
        if (!match.match() || mismatch.match() || mismatch.mismatchedTasks() != 1
                || !match.planFingerprint().equals(mismatch.planFingerprint())) {
            throw new IllegalStateException("Demo verification reports do not show the expected outcomes");
        }
        String sql = Files.readString(docs.resolve("offline-change/change.sql"), StandardCharsets.UTF_8);
        String html = """
                <!doctype html>
                <html lang="en">
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>Try sqlapp — three workflows, one model</title>
                <style>
                  * { box-sizing: border-box; }
                  body { margin: 0; background: #f3f5f7; color: #17212e; font: 17px/1.6 system-ui, sans-serif; }
                  main { max-width: 1000px; margin: auto; padding: 36px 24px 64px; }
                  h1 { font-size: clamp(2rem, 5vw, 3rem); line-height: 1.15; }
                  h2 { margin-top: 0; line-height: 1.3; }
                  a { color: #1451a0; text-underline-offset: 3px; }
                  a:focus-visible { outline: 3px solid #1451a0; outline-offset: 3px; }
                  section { background: white; border: 1px solid #d7dee7; border-radius: 12px; margin: 24px 0; padding: 24px; }
                  pre { overflow-x: auto; padding: 16px; background: #eef2f6; border-radius: 6px; }
                  table { border-collapse: collapse; width: 100%; }
                  th, td { text-align: left; padding: 10px; border-bottom: 1px solid #d7dee7; }
                  .label { color: #43566e; font-size: .85rem; font-weight: 700; letter-spacing: .08em; }
                </style>
                <main>
                  <p class="label">SQLAPP / HANDS-ON DEMOS</p>
                  <h1>Three workflows.<br>One shared database model.</h1>
                  <p>Explore actual outputs from a fictional customer/order model: understand its
                  structure, review a change, then move related data and detect a mismatch.</p>
                  <p>These demos use no external database. The migration runs in two private
                  HSQL memory databases. No generated change SQL is applied to an existing database.</p>
                  <section aria-labelledby="understand">
                    <p class="label">01 / UNDERSTAND AND SHARE</p>
                    <h2 id="understand">Turn structure into a browsable reference</h2>
                    <p>Two related tables become HTML pages, table DDL, clickable SVG diagrams,
                    and downloadable Mermaid sources, all derived from the same Schema XML.</p>
                    <p><a href="../offline-demo/index.html">Browse the database reference</a> ·
                    <a href="../offline-demo/relationships.html">Explore the ER diagram</a></p>
                  </section>
                  <section aria-labelledby="review">
                    <p class="label">02 / REVIEW A CHANGE</p>
                    <h2 id="review">See the model change and the SQL it produces</h2>
                    <p>The desired model adds a nullable EMAIL column to CUSTOMER.
                    This is the actual HSQL change SQL generated by the demo; it was not executed.</p>
                    <pre><code>{{SQL}}</code></pre>
                    <p><a href="../offline-change/before/index.html">Before</a> ·
                    <a href="../offline-change/after/index.html">After</a> ·
                    <a href="../offline-change/change.sql">Full SQL file</a></p>
                  </section>
                  <section aria-labelledby="verify">
                    <p class="label">03 / MOVE AND VERIFY</p>
                    <h2 id="verify">Detect a changed value even when counts match</h2>
                    <p>The migration transfers customers before orders. It then verifies the rows.
                    The demo changes one target customer name and verifies again without repairing it.</p>
                    <table>
                      <caption>Values read from the generated verification reports</caption>
                      <thead><tr><th scope="col">Stage</th><th scope="col">Source rows</th><th scope="col">Target rows</th><th scope="col">Result</th></tr></thead>
                      <tbody>
                        <tr><th scope="row">After transfer</th><td>{{MATCH_SOURCE}}</td><td>{{MATCH_TARGET}}</td><td>MATCH</td></tr>
                        <tr><th scope="row">After target-only name change</th><td>{{MISMATCH_SOURCE}}</td><td>{{MISMATCH_TARGET}}</td><td>MISMATCH — one table</td></tr>
                      </tbody>
                    </table>
                    <p>Ordered row hashes expose the mismatch that row counts alone miss.</p>
                    <p><a href="../offline-migration/execution.json">Execution report</a> ·
                    <a href="../offline-migration/verification-match.json">Matching verification</a> ·
                    <a href="../offline-migration/verification-mismatch.json">Mismatch evidence</a></p>
                  </section>
                  <p>The examples demonstrate outputs and failure visibility, not a performance
                  benchmark or production readiness. A multi-table migration is not one atomic
                  transaction. Resume and repair approval require additional configuration.</p>
                  <p>Keep the whole build/docs directory when sharing this page and its linked artifacts.</p>
                </main>
                </html>
                """;
        html = html.replace("{{SQL}}", escape(sql.strip()))
                .replace("{{MATCH_SOURCE}}", Long.toString(match.expectedRows()))
                .replace("{{MATCH_TARGET}}", Long.toString(match.actualRows()))
                .replace("{{MISMATCH_SOURCE}}", Long.toString(mismatch.expectedRows()))
                .replace("{{MISMATCH_TARGET}}", Long.toString(mismatch.actualRows()));
        Path page = docs.resolve("demo/index.html");
        Files.createDirectories(page.getParent());
        Files.writeString(page, html, StandardCharsets.UTF_8);
        System.out.println("Open " + page.toAbsolutePath());
    }

    private static String escape(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
