/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-hsql.
 */
package com.sqlapp.data.db.dialect.hsql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession;
import com.sqlapp.jdbc.sql.JdbcTreeDataSession.TableOperationMode;

/** HSQLDB integration coverage for ordered batch generated-key propagation. */
class HsqlJdbcTreeDataSessionTest {

	@Test
	void testBatchGeneratedKeysPropagateAndPreparedStatementsAreReused() throws Exception {
		try (Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:tree-data-session", "SA", "")) {
			connection.setAutoCommit(false);
			createTables(connection);
			Schema schema = SchemaUtils.getSchema(connection, "PUBLIC", "PARENT_TABLE", "CHILD_TABLE")
					.orElseThrow();
			Table parent = schema.getTables().get("PARENT_TABLE");
			Table child = schema.getTables().get("CHILD_TABLE");
			Set<PreparedStatement> statements = Collections.newSetFromMap(new IdentityHashMap<>());
			AtomicInteger executions = new AtomicInteger();

			try (JdbcTreeDataSession session = new JdbcTreeDataSession(connection, parent, child)) {
				session.setRootBatchSize(3);
				session.setTableOperationMode(TableOperationMode.INSERT);
				session.setPreparedStatementBeforeExecuteHandler(statement -> {
					statements.add(statement);
					executions.incrementAndGet();
				});
				for (int i = 1; i <= 5; i++) {
					Row parentRow = session.newRow(parent);
					parentRow.put("TXT", "parent-" + i);
					Row childRow = session.newRow(child);
					childRow.put("TXT", "child-" + i);
				}
			}

			assertEquals(2, statements.size());
			assertEquals(4, executions.get());
			try (Statement statement = connection.createStatement();
					ResultSet resultSet = statement.executeQuery("""
							SELECT p.id, p.txt, c.parent_id, c.txt
							FROM parent_table p
							JOIN child_table c ON c.parent_id = p.id
							ORDER BY p.id
							""")) {
				for (long i = 0; i < 5; i++) {
					assertTrue(resultSet.next());
					assertEquals(i, resultSet.getLong(1));
					assertEquals("parent-" + (i + 1), resultSet.getString(2));
					assertEquals(i, resultSet.getLong(3));
					assertEquals("child-" + (i + 1), resultSet.getString(4));
				}
				assertFalse(resultSet.next());
			}
		}
	}

	private void createTables(final Connection connection) throws Exception {
		try (Statement statement = connection.createStatement()) {
			statement.execute("""
					CREATE TABLE parent_table (
						id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						txt VARCHAR(256)
					)
					""");
			statement.execute("""
					CREATE TABLE child_table (
						id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						parent_id BIGINT NOT NULL,
						txt VARCHAR(256),
						CONSTRAINT fk_child_parent FOREIGN KEY (parent_id) REFERENCES parent_table(id)
					)
					""");
			connection.commit();
		}
	}
}
