/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-hsql.
 */
package com.sqlapp.data.db.dialect.hsql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.schemas.IdentityGenerationType;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;

/** Verifies identity generation mode and internal sequence metadata. */
class HsqlIdentityMetadataTest {

	@Test
	void testAlwaysAndByDefaultAreDistinguished() throws Exception {
		try (Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:identity-metadata", "SA", "");
				Statement statement = connection.createStatement()) {
			statement.execute("CREATE TABLE by_default_table (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
			statement.execute("CREATE TABLE always_table (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY)");
			Schema schema = SchemaUtils.getSchema(connection, "PUBLIC", "BY_DEFAULT_TABLE", "ALWAYS_TABLE")
					.orElseThrow();

			assertEquals(IdentityGenerationType.ByDefault,
					schema.getTables().get("BY_DEFAULT_TABLE").getColumns().get("ID").getIdentityGenerationType());
			assertEquals(IdentityGenerationType.Always,
					schema.getTables().get("ALWAYS_TABLE").getColumns().get("ID").getIdentityGenerationType());
			assertNotNull(schema.getTables().get("BY_DEFAULT_TABLE").getColumns().get("ID").getSequence());
			assertNotNull(schema.getTables().get("ALWAYS_TABLE").getColumns().get("ID").getSequence());
		}
	}
}
