/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-command.
 */
package com.sqlapp.data.db.command.migration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.command.test.AbstractDbCommandTest;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.migration.LegacyMigrationLoadPlan;
import com.sqlapp.data.schemas.migration.LegacyMigrationLoadPlan.JoinKey;
import com.sqlapp.data.schemas.migration.LegacyMigrationLoadPlan.LoadDataSet;
import com.sqlapp.data.schemas.migration.LegacyMigrationLoadPlan.LoadField;
import com.zaxxer.hikari.HikariDataSource;

class JdbcTreeStagingLoaderTest extends AbstractDbCommandTest {

	@Test
	void testLoadHierarchyAndCleanupOrphansOnNextRun() throws Exception {
		try (HikariDataSource dataSource = newInternalDataSource();
				Connection connection = dataSource.getConnection()) {
			createTables(connection);
			Schema schema = SchemaUtils.getSchema(connection, "PUBLIC").orElseThrow();
			connection.setAutoCommit(false);
			LegacyMigrationLoadPlan plan = plan();
			plan.setRootCursorStrategy("HOLD");
			JdbcTreeStagingLoader loader = new JdbcTreeStagingLoader(connection, schema, plan);

			assertEquals(2, loader.load());
			assertEquals(2, count(connection, "COMPANY_MASTER"));
			assertEquals(3, count(connection, "EMPLOYEE_LIST"));
			assertEquals(0, count(connection, "TMP_COMPANY_MASTER"));
			assertEquals(3, count(connection, "TMP_EMPLOYEE_LIST"));
			assertEquals(3, count(connection, """
					EMPLOYEE_LIST E
					INNER JOIN COMPANY_MASTER C ON C.ID=E.PARENT_ID
					WHERE (C.COMPANY_ID='C001' AND E.EMP_ID IN ('E001','E002'))
					   OR (C.COMPANY_ID='C002' AND E.EMP_ID='E003')
					"""));

			assertEquals(0, new JdbcTreeStagingLoader(connection, schema, plan).load());
			assertEquals(0, count(connection, "TMP_EMPLOYEE_LIST"));
		}
	}

	@Test
	void testMarkRootsLoadedWhenStagingDeletionDisabled() throws Exception {
		try (HikariDataSource dataSource = newInternalDataSource();
				Connection connection = dataSource.getConnection()) {
			createTables(connection);
			Schema schema = SchemaUtils.getSchema(connection, "PUBLIC").orElseThrow();
			LegacyMigrationLoadPlan plan = plan();
			plan.setDeleteCommittedRoots(false);
			plan.setRootCursorStrategy("REOPEN");
			connection.setAutoCommit(false);

			assertEquals(2, new JdbcTreeStagingLoader(connection, schema, plan).load());
			assertEquals(2, count(connection,
					"TMP_COMPANY_MASTER WHERE SQLAPP_LOAD_STATUS='LOADED'"));
			assertEquals(3, count(connection, "TMP_EMPLOYEE_LIST"));
			assertEquals(0, new JdbcTreeStagingLoader(connection, schema, plan).load());
		}
	}

	private void createTables(Connection connection) throws Exception {
		dropTables(connection, "EMPLOYEE_LIST");
		dropTables(connection, "COMPANY_MASTER");
		dropTables(connection, "TMP_EMPLOYEE_LIST");
		dropTables(connection, "TMP_COMPANY_MASTER");
		executeSql(connection, """
				CREATE TABLE COMPANY_MASTER
				(
					  ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
					, COMPANY_ID VARCHAR(4) NOT NULL
					, CONSTRAINT UK_COMPANY_MASTER UNIQUE (COMPANY_ID)
				)
				""");
		executeSql(connection, """
				CREATE TABLE EMPLOYEE_LIST
				(
					  ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
					, PARENT_ID INT NOT NULL
					, EMP_ID VARCHAR(6) NOT NULL
					, FOREIGN KEY (PARENT_ID) REFERENCES COMPANY_MASTER(ID)
					, CONSTRAINT UK_EMPLOYEE_LIST UNIQUE (PARENT_ID, EMP_ID)
				)
				""");
		executeSql(connection, """
				CREATE TABLE TMP_COMPANY_MASTER
				(
					  COMPANY_ID VARCHAR(4)
					, SQLAPP_LOAD_STATUS VARCHAR(16) DEFAULT 'PENDING' NOT NULL
					, SQLAPP_LOADED_AT TIMESTAMP
				)
				""");
		executeSql(connection, """
				CREATE TABLE TMP_EMPLOYEE_LIST
				(
					  COMPANY_ID VARCHAR(4)
					, EMP_ID VARCHAR(6)
					, SQLAPP_LOADED_AT TIMESTAMP
				)
				""");
		executeSql(connection,
				"INSERT INTO TMP_COMPANY_MASTER(COMPANY_ID) VALUES ('C001'),('C002')");
		executeSql(connection, """
				INSERT INTO TMP_EMPLOYEE_LIST(COMPANY_ID,EMP_ID)
				VALUES ('C001','E001'),('C001','E002'),('C002','E003')
				""");
		connection.commit();
	}

	private LegacyMigrationLoadPlan plan() {
		LegacyMigrationLoadPlan plan = new LegacyMigrationLoadPlan();
		plan.setTableOperationMode("INSERT_IGNORE");
		plan.setRootBatchSize(1);
		plan.setCommitEveryRootBatches(2);
		LoadDataSet company = dataSet("company", "COMPANY_MASTER", "TMP_COMPANY_MASTER", null, 0);
		company.getSourceBusinessKey().add("COMPANY_ID");
		company.getFields().add(field(1, "COMPANY_ID", "COMPANY_ID", true, false, "COPY"));
		company.getFields().add(field(0, "ID", "ID", false, true, "GENERATE"));
		plan.getDataSets().add(company);
		LoadDataSet employee = dataSet("employee", "EMPLOYEE_LIST", "TMP_EMPLOYEE_LIST", company.getId(), 1);
		employee.getFields().add(field(1, "COMPANY_ID", null, true, false, "DROP"));
		employee.getFields().add(field(2, "EMP_ID", "EMP_ID", true, false, "COPY"));
		employee.getFields().add(field(0, "ID", "ID", false, true, "GENERATE"));
		employee.getFields().add(field(0, "PARENT_ID", "PARENT_ID", false, true, "GENERATE"));
		JoinKey key = new JoinKey();
		key.setParentStagingColumn("COMPANY_ID");
		key.setChildStagingColumn("COMPANY_ID");
		key.setTargetForeignKeyColumn("PARENT_ID");
		employee.getParentJoinKeys().add(key);
		plan.getDataSets().add(employee);
		return plan;
	}

	private LoadDataSet dataSet(String id, String target, String staging, String parent, int order) {
		LoadDataSet dataSet = new LoadDataSet();
		dataSet.setId(id);
		dataSet.setTargetSchema("PUBLIC");
		dataSet.setTargetTable(target);
		dataSet.setStagingTable(staging);
		dataSet.setParentDataSetId(parent);
		dataSet.setHierarchyDepth(order);
		dataSet.setLoadOrder(order);
		return dataSet;
	}

	private LoadField field(int position, String staging, String target, boolean extracted,
			boolean generated, String action) {
		LoadField field = new LoadField();
		field.setCsvPosition(position);
		field.setStagingColumn(staging);
		field.setTargetColumn(target);
		field.setExtracted(extracted);
		field.setTargetGenerated(generated);
		field.setAction(action);
		return field;
	}

	private int count(Connection connection, String expression) throws Exception {
		try (var statement = connection.createStatement();
				var resultSet = statement.executeQuery("SELECT COUNT(*) FROM " + expression)) {
			assertTrue(resultSet.next());
			return resultSet.getInt(1);
		}
	}
}
