/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-hsql.
 */
package com.sqlapp.data.db.dialect.hsql.metadata;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.DriverManager;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.util.CommonUtils;

/** HSQLDB 2.7 catalog metadata round trip. */
class HsqlMetadataRoundTripTest {

	@Test
	void testSchemaObjectsRoundTrip() throws Exception {
		try (var connection = DriverManager.getConnection(
				"jdbc:hsqldb:mem:metadata-round-trip", "SA", "");
				var statement = connection.createStatement()) {
			statement.execute("CREATE SEQUENCE ORDER_SEQ START WITH 50 INCREMENT BY 5");
			statement.execute("CREATE TABLE PARENT_TABLE (ID BIGINT PRIMARY KEY)");
			statement.execute("""
					CREATE TABLE METADATA_TABLE (
					  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					  NAME VARCHAR(100) DEFAULT 'unknown' NOT NULL,
					  PARENT_ID BIGINT,
					  CONSTRAINT UK_METADATA_NAME UNIQUE (NAME),
					  CONSTRAINT CK_METADATA_NAME CHECK (NAME <> ''),
					  CONSTRAINT FK_METADATA_PARENT FOREIGN KEY (PARENT_ID)
					    REFERENCES PARENT_TABLE(ID))
					""");
			statement.execute("CREATE INDEX IDX_METADATA_NAME ON METADATA_TABLE(NAME DESC)");
			statement.execute("CREATE VIEW METADATA_VIEW AS SELECT ID, NAME FROM METADATA_TABLE");
			statement.execute("CREATE FUNCTION ADD_ONE(V INTEGER) RETURNS INTEGER RETURN V + 1");
			statement.execute("""
					CREATE PROCEDURE RENAME_ROW(IN P_ID BIGINT, IN P_NAME VARCHAR(100))
					MODIFIES SQL DATA UPDATE METADATA_TABLE SET NAME = P_NAME WHERE ID = P_ID
					""");

			var dialect = DialectResolver.getInstance().getDialect(connection);
			var reader = dialect.getCatalogReader().getSchemaReader();
			reader.setSchemaName("PUBLIC");
			Schema schema = CommonUtils.first(reader.getAllFull(connection));

			var table = schema.getTables().get("METADATA_TABLE");
			assertNotNull(table);
			assertNotNull(table.getIndexes().get("IDX_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("UK_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("CK_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("FK_METADATA_PARENT"));
			assertEquals("'unknown'", table.getColumns().get("NAME").getDefaultValue());

			var view = schema.getViews().get("METADATA_VIEW");
			assertNotNull(view);
			assertEquals(2, view.getColumns().size());
			assertTrue(String.join("\n", view.getStatement()).contains("METADATA_TABLE"),
					view.getStatement().toString());
			assertNotNull(schema.getSequences().get("ORDER_SEQ"));

			var function = schema.getFunctions().get("ADD_ONE");
			assertNotNull(function);
			assertEquals(1, function.getArguments().size());
			assertNotNull(function.getStatement());
			var procedure = schema.getProcedures().get("RENAME_ROW");
			assertNotNull(procedure);
			assertEquals(2, procedure.getArguments().size());
			assertNotNull(procedure.getStatement());
		}
	}
}
