INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (1, 'abc');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (2, 'def');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (3, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (4, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (5, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (6, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (7, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (8, 'ghi');
INSERT INTO TAB2 ( INTEGER_COL, VARCHAR_COL ) VALUES (9, 'ghi');

