/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.data.db.dialect.test.firebird;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.sql.DriverManager;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;
import com.sqlapp.jdbc.bulk.BulkInsertResolver;
import com.sqlapp.jdbc.bulk.BulkOption;

class FirebirdBulkInsertTest {
	private static final String PASSWORD = "masterkey";
	private static final GenericContainer<?> FIREBIRD = ReusableTestcontainers.configure(
			new GenericContainer<>(DockerImageName.parse("jacobalberty/firebird:v5.0"))
					.withEnv("ISC_PASSWORD", PASSWORD).withEnv("FIREBIRD_DATABASE", "test.fdb")
					.withExposedPorts(3050).waitingFor(Wait.forListeningPort()));

	@BeforeAll static void start() { ReusableTestcontainers.start(FIREBIRD); }
	@AfterAll static void stop() { ReusableTestcontainers.stop(FIREBIRD); }

	@Test
	void insertsBatchesAndIdentityValues() throws Exception {
		final String url = "jdbc:firebirdsql://localhost:" + FIREBIRD.getMappedPort(3050)
				+ "//firebird/data/test.fdb?encoding=UTF8";
		try (var connection = DriverManager.getConnection(url, "SYSDBA", PASSWORD);
				var statement = connection.createStatement()) {
			try { statement.execute("DROP TABLE SQLAPP_BULK_FIREBIRD"); }
			catch (java.sql.SQLException ignored) { }
			statement.execute("CREATE TABLE SQLAPP_BULK_FIREBIRD (ID INTEGER GENERATED BY "
					+ "DEFAULT AS IDENTITY PRIMARY KEY, TXT VARCHAR(200), NULLABLE_VALUE VARCHAR(20), "
					+ "EMPTY_VALUE VARCHAR(20), PAYLOAD VARBINARY(20))");
			final Table generated = createTable();
			generated.getRows().add(row -> { row.put("TXT", "日本語\nline");
				row.put("NULLABLE_VALUE", null); row.put("EMPTY_VALUE", "");
				row.put("PAYLOAD", new byte[] { 0, (byte) 0xff }); });
			assertEquals(1, BulkInsertResolver.execute(connection, generated,
					BulkOption.builder().batchSize(2).build()));
			final Table explicit = createTable();
			explicit.getRows().add(row -> { row.put("ID", 42); row.put("TXT", "explicit");
				row.put("EMPTY_VALUE", ""); row.put("PAYLOAD", new byte[] { 1 }); });
			assertEquals(1, BulkInsertResolver.execute(connection, explicit,
					BulkOption.builder().keepIdentity(true).build()));
			try (var rs = statement.executeQuery("SELECT * FROM SQLAPP_BULK_FIREBIRD WHERE ID=1")) {
				rs.next(); assertEquals("日本語\nline", rs.getString("TXT"));
				assertNull(rs.getString("NULLABLE_VALUE")); assertEquals("", rs.getString("EMPTY_VALUE"));
				assertArrayEquals(new byte[] { 0, (byte) 0xff }, rs.getBytes("PAYLOAD"));
			}
		}
	}

	private static Table createTable() {
		final Table table = new Table("SQLAPP_BULK_FIREBIRD");
		table.getColumns().add(new Column("ID").setDataType(DataType.INT).setIdentity(true));
		table.getColumns().add(new Column("TXT").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("NULLABLE_VALUE").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("EMPTY_VALUE").setDataType(DataType.VARCHAR));
		table.getColumns().add(new Column("PAYLOAD").setDataType(DataType.VARBINARY));
		return table;
	}
}
