/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-dialect-test.
 */
package com.sqlapp.data.db.dialect.test.firebird;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.db.dialect.firebird.Firebird30;
import com.sqlapp.data.db.dialect.test.ReusableTestcontainers;
import com.sqlapp.data.schemas.ForeignKeyConstraint;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.UniqueConstraint;
import com.sqlapp.jdbc.sql.ParameterDirection;

/** Firebird 3 compatibility coverage for the metadata reader tree. */
class Firebird30MetadataReaderTest {
	private static final String PASSWORD = "masterkey";
	private static final GenericContainer<?> FIREBIRD = ReusableTestcontainers.configure(
			new GenericContainer<>(DockerImageName.parse("jacobalberty/firebird:v3.0"))
					.withEnv("ISC_PASSWORD", PASSWORD)
					.withEnv("FIREBIRD_DATABASE", "test.fdb")
					.withExposedPorts(3050)
					.waitingFor(Wait.forListeningPort()));

	@BeforeAll
	static void startContainer() {
		ReusableTestcontainers.start(FIREBIRD);
	}

	@AfterAll
	static void stopContainer() {
		ReusableTestcontainers.stop(FIREBIRD);
	}

	@Test
	void readsCoreSchemaObjectsWithThe30Reader() throws SQLException {
		try (Connection connection = createConnection();
				Statement statement = connection.createStatement()) {
			createObjects(statement);
			assertInstanceOf(Firebird30.class,
					DialectResolver.getInstance().getDialect(connection));
			var schema = SchemaUtils.getSchema(connection, null, "METADATA30_PARENT",
					"METADATA30_CHILD", "METADATA30_VIEW", "METADATA30_PROCEDURE",
					"METADATA30_FUNCTION").orElseThrow();

			var parent = schema.getTables().get("METADATA30_PARENT");
			assertNotNull(parent);
			assertTrue(parent.getColumns().get("ID").isIdentity());
			var primaryKey = assertInstanceOf(UniqueConstraint.class,
					parent.getConstraints().getPrimaryKeyConstraint());
			assertEquals("ID", primaryKey.getColumns().get(0).getName());

			var child = schema.getTables().get("METADATA30_CHILD");
			var foreignKey = child.getConstraints().stream()
					.filter(ForeignKeyConstraint.class::isInstance)
					.map(ForeignKeyConstraint.class::cast).findFirst().orElseThrow();
			assertEquals("PARENT_ID", foreignKey.getColumns().get(0).getName());
			assertEquals("ID", foreignKey.getRelatedColumns().get(0).getName());
			assertEquals("CODE", child.getIndexes().get("IDX_METADATA30_CODE")
					.getColumns().get(0).getName());

			var view = schema.getViews().get("METADATA30_VIEW");
			assertNotNull(view);
			assertTrue(String.join("\n", view.getStatement()).toUpperCase()
					.contains("METADATA30_PARENT"));
			assertEquals(2, view.getColumns().size());

			var procedure = schema.getProcedures().get("METADATA30_PROCEDURE");
			assertNotNull(procedure);
			assertEquals(ParameterDirection.Input,
					procedure.getArguments().get("P_ID").getDirection());
			assertTrue(String.join("\n", procedure.getStatement()).toUpperCase()
					.contains("P_VALUE = P_ID + 1"));

			var function = schema.getFunctions().get("METADATA30_FUNCTION");
			assertNotNull(function);
			assertEquals(DataType.INT,
					function.getArguments().get("P_VALUE").getDataType());
			assertEquals(DataType.INT, function.getReturning().getDataType());
			assertTrue(String.join("\n", function.getStatement()).toUpperCase()
					.contains("RETURN P_VALUE + 1"));
		}
	}

	private Connection createConnection() throws SQLException {
		String url = "jdbc:firebirdsql://localhost:" + FIREBIRD.getMappedPort(3050)
				+ "//firebird/data/test.fdb?encoding=UTF8";
		return DriverManager.getConnection(url, "SYSDBA", PASSWORD);
	}

	private void createObjects(final Statement statement) throws SQLException {
		statement.execute("CREATE TABLE metadata30_parent ("
				+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(40))");
		statement.execute("CREATE TABLE metadata30_child (id BIGINT PRIMARY KEY, "
				+ "parent_id BIGINT NOT NULL, code VARCHAR(40), "
				+ "CONSTRAINT fk_metadata30_parent FOREIGN KEY (parent_id) "
				+ "REFERENCES metadata30_parent(id))");
		statement.execute("CREATE INDEX idx_metadata30_code ON metadata30_child(code)");
		statement.execute("CREATE VIEW metadata30_view AS "
				+ "SELECT id, code FROM metadata30_parent");
		statement.execute("CREATE PROCEDURE metadata30_procedure(p_id INTEGER) "
				+ "RETURNS (p_value INTEGER) AS BEGIN p_value = p_id + 1; SUSPEND; END");
		statement.execute("CREATE FUNCTION metadata30_function(p_value INTEGER) "
				+ "RETURNS INTEGER AS BEGIN RETURN p_value + 1; END");
	}
}
