plugins {
	id ('com.sqlapp.maven-deploy')
}

dependencies {
	implementation project(':sqlapp-core')
	testImplementation project(':sqlapp-core-test')

	// Source: https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
	implementation("com.microsoft.sqlserver:mssql-jdbc:13.5.0.jre11-preview")
}

javadoc {
	include '**/sqlserver/*'
}