/**
 * Copyright (C) 2007-2025 Tatsuo Satoh &lt;multisqllib@gmail.com&gt;
 *
 * This file is part of sqlapp-core.
 *
 * sqlapp-core is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sqlapp-core is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with sqlapp-core.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
 */

package com.sqlapp.data.db.command;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.util.Optional;

import org.junit.jupiter.api.Test;

import com.sqlapp.AbstractDbTest;
import com.sqlapp.data.parameter.ParametersContext;
import com.sqlapp.data.schemas.Row;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;
import com.sqlapp.data.schemas.Table;

class JdbcBatchTableIterateHanderTest extends AbstractDbTest {

	private String CREATE_TABLE = """
			CREATE TABLE TAB
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  ,  TXT VARCHAR(256)
			)""";
	private String CREATE_TABLE_1 = """
			CREATE TABLE TAB_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_1_1 = """
			CREATE TABLE TAB_1_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB_1(ID)
			)""";
	private String CREATE_TABLE_2 = """
			CREATE TABLE TAB_2
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB(ID)
			)""";
	private String CREATE_TABLE_2_1 = """
			CREATE TABLE TAB_2_1
			(
				  ID INT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1, INCREMENT BY 3 ) PRIMARY KEY
				  , PARENT_ID INT NOT NULL
				  ,  TXT VARCHAR(256)
				, FOREIGN KEY(PARENT_ID)
				REFERENCES TAB_2(ID)
			)""";

	/**
	 * INSERTして自動生成されたキーを使って、そのままUPDATEを行う
	 * 
	 * @throws SQLException
	 */
	@Test
	void testInsertUpdateWithGeneratedKey() throws SQLException {
		final ParametersContext context = new ParametersContext();
		testDb(connection -> {
			executeSql(connection, CREATE_TABLE);
			executeSql(connection, CREATE_TABLE_1);
			executeSql(connection, CREATE_TABLE_1_1);
			executeSql(connection, CREATE_TABLE_2);
			executeSql(connection, CREATE_TABLE_2_1);
			Optional<Schema> schemaOption = SchemaUtils.getSchema(connection, "PUBLIC");
			assertTrue(schemaOption.isPresent());
			Schema schema = schemaOption.get();
			Table tab = schema.getTables().get("TAB");
			Table tab1 = schema.getTables().get("TAB_1");
			Table tab1_1 = schema.getTables().get("TAB_1_1");
			Table tab2 = schema.getTables().get("TAB_2");
			Table tab2_1 = schema.getTables().get("TAB_2_1");
			for (int i = 0; i < 10; i++) {
				Row row = tab.newRow();
				row.put("TXT", "TAB_TXT" + i);
				tab.getRows().add(row);
				for (int i1 = 0; i1 < 2; i1++) {
					Row row1 = tab1.newRow(row);
					row1.put("TXT", "TAB_1_TXT" + i + "_" + i1);
					tab1.getRows().add(row1);
					for (int i1_1 = 0; i1_1 < 3; i1_1++) {
						Row row1_1 = tab1_1.newRow(row1);
						row1_1.put("TXT", "TAB_1_1_TXT" + i + "_" + i1 + "_" + i1_1);
						tab1_1.getRows().add(row1_1);
					}
				}
				for (int i2 = 0; i2 < 3; i2++) {
					Row row2 = tab2.newRow(row);
					row2.put("TXT", "TAB_1_TXT" + i + "_" + i2);
					tab2.getRows().add(row2);
					for (int i2_1 = 0; i2_1 < 3; i2_1++) {
						Row row2_1 = tab2_1.newRow(row2);
						row2_1.put("TXT", "TAB_2_1_TXT" + i + "_" + i2 + "_" + i2_1);
						tab2_1.getRows().add(row2_1);
					}
				}

			}
			assertEquals(5, schema.getTables().size());
		}, (connection) -> {
			this.dropTables(connection, "TAB_2_1");
			this.dropTables(connection, "TAB_2");
			this.dropTables(connection, "TAB_1_1");
			this.dropTables(connection, "TAB_1");
			this.dropTables(connection, "TAB");
		});
	}

	public static class JdbcHierarchicalBatch {

	}

}
