/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-derby.
 */
package com.sqlapp.data.db.dialect.derby;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import org.junit.jupiter.api.Test;

/** Verifies Derby's batch generated-key behavior used by tree inserts. */
class DerbyBatchGeneratedKeysTest {

	@Test
	void testBatchReturnsOnlyLastGeneratedIdentity() throws Exception {
		try (Connection connection = DriverManager.getConnection("jdbc:derby:memory:batch-generated-keys;create=true")) {
			connection.createStatement().execute("""
					CREATE TABLE test_table (
						id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						txt VARCHAR(30)
					)
					""");
			try (PreparedStatement statement = connection.prepareStatement(
					"INSERT INTO test_table(txt) VALUES(?)", Statement.RETURN_GENERATED_KEYS)) {
				for (int i = 0; i < 5; i++) {
					statement.setString(1, "row-" + i);
					statement.addBatch();
				}
				int[] counts = statement.executeBatch();
				assertEquals(5, counts.length);
				try (ResultSet keys = statement.getGeneratedKeys()) {
					assertTrue(keys.next());
					assertEquals(5L, keys.getLong(1));
					assertFalse(keys.next());
				}
			}
		}
	}
}
