/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-derby.
 */
package com.sqlapp.data.db.dialect.derby;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.DriverManager;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.db.dialect.DialectResolver;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.util.CommonUtils;

/** Derby 10.17 catalog metadata round trip. */
class DerbyMetadataRoundTripTest {
	@Test
	void testSchemaObjectsRoundTrip() throws Exception {
		try (var connection = DriverManager.getConnection(
				"jdbc:derby:memory:metadata-round-trip;create=true");
				var statement = connection.createStatement()) {
			statement.execute("CREATE SEQUENCE ORDER_SEQ AS BIGINT START WITH 50 INCREMENT BY 5");
			statement.execute("CREATE TABLE PARENT_TABLE (ID BIGINT PRIMARY KEY)");
			statement.execute("CREATE TABLE AUDIT_TABLE (ID BIGINT)");
			statement.execute("""
					CREATE TABLE METADATA_TABLE (
					  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					  NAME VARCHAR(100) DEFAULT 'unknown' NOT NULL,
					  PARENT_ID BIGINT,
					  CONSTRAINT UK_METADATA_NAME UNIQUE (NAME),
					  CONSTRAINT CK_METADATA_NAME CHECK (NAME <> ''),
					  CONSTRAINT FK_METADATA_PARENT FOREIGN KEY (PARENT_ID)
					    REFERENCES PARENT_TABLE(ID))
					""");
			statement.execute("CREATE INDEX IDX_METADATA_NAME ON METADATA_TABLE(NAME DESC)");
			statement.execute("CREATE VIEW METADATA_VIEW AS SELECT ID, NAME FROM METADATA_TABLE");
			statement.execute("""
					CREATE TRIGGER METADATA_TRIGGER AFTER INSERT ON METADATA_TABLE
					REFERENCING NEW AS N FOR EACH ROW
					INSERT INTO AUDIT_TABLE(ID) VALUES (N.ID)
					""");

			var dialect = DialectResolver.getInstance().getDialect(connection);
			var catalogReader = dialect.getCatalogReader();
			var reader = catalogReader.getSchemaReader();
			reader.setSchemaName("APP");
			var tableReader = reader.getTableReader();
			tableReader.setSchemaName("APP");
			tableReader.setObjectName("METADATA_TABLE");
			var uniqueConstraints = tableReader.getUniqueConstraintReader()
					.getAllFull(connection);
			assertTrue(uniqueConstraints.stream().anyMatch(
					constraint -> "UK_METADATA_NAME".equals(constraint.getName())),
					uniqueConstraints.toString());
			var uniqueConstraint = uniqueConstraints.stream().filter(
					constraint -> "UK_METADATA_NAME".equals(constraint.getName()))
					.findFirst().orElseThrow();
			assertEquals("APP", uniqueConstraint.getSchemaName());
			assertEquals("METADATA_TABLE", uniqueConstraint.getTableName());
			assertEquals(1, uniqueConstraint.getColumns().size(),
					uniqueConstraint.toString());
			var checkConstraints = tableReader.getCheckConstraintReader()
					.getAllFull(connection);
			assertTrue(checkConstraints.stream().anyMatch(
					constraint -> "CK_METADATA_NAME".equals(constraint.getName())),
					checkConstraints.toString());
			var foreignKeys = tableReader.getForeignKeyConstraintReader()
					.getAllFull(connection);
			var foreignKey = foreignKeys.stream().filter(
					constraint -> "FK_METADATA_PARENT".equals(constraint.getName()))
					.findFirst().orElseThrow();
			assertEquals("APP", foreignKey.getSchemaName());
			assertEquals("METADATA_TABLE", foreignKey.getTableName());
			assertEquals(1, foreignKey.getColumns().size(), foreignKey.toString());
			assertEquals(1, foreignKey.getRelatedColumns().size(),
					foreignKey.toString());
			var detailedTable = CommonUtils.first(
					tableReader.getAllFull(connection));
			assertEquals(uniqueConstraint.getCatalogName(),
					detailedTable.getCatalogName());
			assertEquals(uniqueConstraint.getSchemaName(),
					detailedTable.getSchemaName());
			assertEquals(uniqueConstraint.getTableName(), detailedTable.getName());
			assertNotNull(detailedTable.getIndexes().get("IDX_METADATA_NAME"));
			assertNotNull(detailedTable.getConstraints().get("UK_METADATA_NAME"));
			assertNotNull(detailedTable.getConstraints().get("CK_METADATA_NAME"));
			assertNotNull(detailedTable.getConstraints().get("FK_METADATA_PARENT"));
			Schema schema = CommonUtils.first(reader.getAllFull(connection));

			var table = schema.getTables().get("METADATA_TABLE");
			assertNotNull(table);
			assertEquals("APP", table.getSchemaName());
			assertNotNull(table.getIndexes().get("IDX_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("UK_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("CK_METADATA_NAME"));
			assertNotNull(table.getConstraints().get("FK_METADATA_PARENT"));
			assertEquals("'unknown'", table.getColumns().get("NAME").getDefaultValue());
			assertNotNull(schema.getSequences().get("ORDER_SEQ"));

			var view = schema.getViews().get("METADATA_VIEW");
			assertNotNull(view);
			assertNotNull(view.getDefinition());
			assertTrue(String.join("\n", view.getDefinition()).contains("METADATA_TABLE"),
					view.getDefinition().toString());

			var trigger = schema.getTriggers().get("METADATA_TRIGGER");
			assertNotNull(trigger);
			assertEquals("METADATA_TABLE", trigger.getTableName());
			assertEquals("AFTER", trigger.getActionTiming());
			assertTrue(trigger.getEventManipulation().contains("INSERT"));
			assertNotNull(trigger.getDefinition());
		}
	}
}
