/*
 * Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com>
 *
 * This file is part of sqlapp-core-derby.
 */
package com.sqlapp.data.db.dialect.derby;

import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

import org.junit.jupiter.api.Test;

import com.sqlapp.data.schemas.IdentityGenerationType;
import com.sqlapp.data.schemas.Schema;
import com.sqlapp.data.schemas.SchemaUtils;

/** Documents Derby's catalog representation of identity generation modes. */
class DerbyIdentityCatalogTest {

	@Test
	void testCatalogDistinguishesAlwaysAndByDefault() throws Exception {
		try (Connection connection = DriverManager.getConnection("jdbc:derby:memory:identity-catalog;create=true")) {
			connection.createStatement().execute(
					"CREATE TABLE always_table (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY)");
			connection.createStatement().execute(
					"CREATE TABLE default_table (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
			String always;
			String byDefault;
			try (ResultSet resultSet = connection.createStatement().executeQuery("""
						SELECT t.tablename, CAST(c.columndefault AS VARCHAR(32672))
						FROM sys.syscolumns c
						JOIN sys.systables t ON t.tableid = c.referenceid
						WHERE t.tablename IN ('ALWAYS_TABLE', 'DEFAULT_TABLE')
						ORDER BY t.tablename
						""")) {
				resultSet.next();
				always = resultSet.getString(2);
				resultSet.next();
				byDefault = resultSet.getString(2);
			}
			assertNotEquals(always, byDefault);
			Schema schema = SchemaUtils.getSchema(connection, "APP", "ALWAYS_TABLE", "DEFAULT_TABLE").orElseThrow();
			assertEquals(IdentityGenerationType.Always,
					schema.getTables().get("ALWAYS_TABLE").getColumns().get("ID").getIdentityGenerationType());
			assertEquals(IdentityGenerationType.ByDefault,
					schema.getTables().get("DEFAULT_TABLE").getColumns().get("ID").getIdentityGenerationType());
		}
	}
}
