/* Copyright (C) 2026-2026 Tatsuo Satoh <multisqllib@gmail.com> */
package com.sqlapp.jdbc.bulk;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.Test;

import com.sqlapp.AbstractDbTest;
import com.sqlapp.data.db.datatype.DataType;
import com.sqlapp.data.schemas.Column;
import com.sqlapp.data.schemas.Table;

class JdbcBatchBulkInsertExecutorTest extends AbstractDbTest {
	@Test
	void insertsExplicitValuesUsingDialectInsertFactory() throws Exception {
		testDb(connection -> {
			execute(connection, "CREATE TABLE SQLAPP_BATCH_FACTORY_TEST ("
					+ "ID INTEGER NOT NULL, VALUE VARCHAR(32) DEFAULT 'database-default')");
			final Table table = new Table("SQLAPP_BATCH_FACTORY_TEST");
			table.getColumns().add(new Column("ID").setDataType(DataType.INT)
					.setNotNull(true));
			table.getColumns().add(new Column("VALUE").setDataType(DataType.VARCHAR)
					.setLength(32).setDefaultValue("'model-default'"));
			final var first = table.newRow();
			first.put("ID", 1);
			first.put("VALUE", "first");
			table.getRows().add(first);
			final var second = table.newRow();
			second.put("ID", 2);
			second.put("VALUE", "second");
			table.getRows().add(second);

			final long affected = new JdbcBatchBulkInsertExecutor(getDialect(connection))
					.execute(connection, table, BulkOption.builder().batchSize(1).build());

			assertEquals(2, affected);
			try (var statement = connection.prepareStatement(
					"SELECT VALUE FROM SQLAPP_BATCH_FACTORY_TEST WHERE ID = ?")) {
				statement.setInt(1, 2);
				try (var resultSet = statement.executeQuery()) {
					resultSet.next();
					assertEquals("second", resultSet.getString(1));
				}
			}
		});
	}

	@Test
	void preservesKeepIdentityBehaviorWithDialectInsertFactory() throws Exception {
		testDb(connection -> {
			execute(connection, "CREATE TABLE SQLAPP_BATCH_IDENTITY_TEST ("
					+ "ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
					+ "VALUE VARCHAR(32))");
			final Table generated = identityTable();
			final var generatedRow = generated.newRow();
			generatedRow.put("ID", 100);
			generatedRow.put("VALUE", "generated");
			generated.getRows().add(generatedRow);
			final var executor = new JdbcBatchBulkInsertExecutor(getDialect(connection));
			executor.execute(connection, generated, BulkOption.defaults());

			final Table explicit = identityTable();
			final var explicitRow = explicit.newRow();
			explicitRow.put("ID", 200);
			explicitRow.put("VALUE", "explicit");
			explicit.getRows().add(explicitRow);
			executor.execute(connection, explicit,
					BulkOption.builder().keepIdentity(true).build());

			try (var statement = connection.createStatement();
					var resultSet = statement.executeQuery(
							"SELECT ID, VALUE FROM SQLAPP_BATCH_IDENTITY_TEST ORDER BY VALUE")) {
				resultSet.next();
				assertEquals(200, resultSet.getInt(1));
				assertEquals("explicit", resultSet.getString(2));
				resultSet.next();
				assertEquals(0, resultSet.getInt(1));
				assertEquals("generated", resultSet.getString(2));
			}
		});
	}

	@Test
	void keepsExplicitAutoIncrementTypeInTheGeneratedInsertContract() throws Exception {
		testDb(connection -> {
			final Table table = new Table("SQLAPP_SERIAL_INSERT_TEST");
			final Column id = new Column("ID").setDataType(DataType.SERIAL)
					.setIdentity(true);
			final Column value = new Column("VALUE").setDataType(DataType.VARCHAR);
			table.getColumns().add(id);
			table.getColumns().add(value);
			final var dialect = getDialect(connection);

			final class TestExecutor extends JdbcBatchBulkInsertExecutor {
				private TestExecutor() {
					super(dialect);
				}

				private String sql() {
					return createInsertSql(table, List.of(id, value));
				}
			}
			final String sql = new TestExecutor().sql();
			assertEquals(2, sql.chars().filter(ch -> ch == '?').count(), sql);
		});
	}

	private static Table identityTable() {
		final Table table = new Table("SQLAPP_BATCH_IDENTITY_TEST");
		table.getColumns().add(new Column("ID").setDataType(DataType.INT)
				.setIdentity(true));
		table.getColumns().add(new Column("VALUE").setDataType(DataType.VARCHAR)
				.setLength(32));
		return table;
	}
}
